import React, { createContext, useContext, useEffect, useState } from 'react';

export type Language = 'en' | 'ar' | 'es' | 'fr' | 'hi' | 'de' | 'pt' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};

interface LanguageProviderProps {
  children: React.ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language') as Language;
    return saved || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    // Set document direction for RTL languages
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language]?.[key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

// Translation dictionary
const translations = {
  en: {
    // Header
    'search.placeholder': 'Search markets, bots...',
    'market.status': 'Markets Open',
    'user.name': 'John Doe',
    
    // Sidebar
    'app.name': 'CryptoBot Pro',
    'dashboard': 'Dashboard',
    'overview': 'Overview',
    'performance.summary': 'Performance Summary',
    'market.overview': 'Market Overview',
    
    'bots': 'Bots',
    'create.new.bot': 'Create New Bot',
    'my.bots': 'My Bots',
    'bot.performance': 'Bot Performance',
    'strategy.templates': 'Strategy Templates',
    
    'trading': 'Trading',
    'manual.trading': 'Manual Trading',
    'signal.trading': 'Signal Trading',
    'paper.trading': 'Paper Trading',
    
    'markets': 'Markets',
    'live.charts': 'Live Charts',
    'market.scanner': 'Market Scanner',
    'watchlist': 'Watchlist',
    'price.alerts': 'Price Alerts',
    
    'exchanges.api': 'Exchanges & API',
    'connect.exchange': 'Connect Exchange',
    'api.management': 'API Management',
    'sync.balances': 'Sync Balances',
    
    'alerts': 'Alerts',
    'create.alert': 'Create Alert',
    'notification.settings': 'Notification Settings',
    'alert.logs': 'Alert Logs',
    
    'strategy.builder': 'Strategy Builder',
    'build.strategy': 'Build Strategy',
    'saved.strategies': 'Saved Strategies',
    'backtesting': 'Backtesting',
    'marketplace': 'Marketplace',
    
    'security.settings': 'Security & Settings',
    'profile.settings': 'Profile Settings',
    'two.factor.auth': 'Two-Factor Auth',
    'theme.settings': 'Theme Settings',
    'session.logs': 'Session Logs',
    
    'help': 'Help',
    'documentation': 'Documentation',
    'contact.support': 'Contact Support',
    'bug.reports': 'Bug Reports',
    'community': 'Community',
    
    // Page content
    'welcome.back': 'Welcome back! Here\'s an overview of your crypto trading activity.',
    'total.pnl': 'Total P&L',
    'total.roi': 'Total ROI',
    'win.rate': 'Win Rate',
    'total.trades': 'Total Trades',
    'create.bot': 'Create Bot',
    'bot.name': 'Bot Name',
    'trading.pair': 'Trading Pair',
    'strategy.type': 'Strategy Type',
    'investment.amount': 'Investment Amount',
    'select.trading.pair': 'Select trading pair',
    'select.strategy': 'Select strategy',
    'enter.amount.usdt': 'Enter amount in USDT',
    'enter.bot.name': 'Enter bot name',
    
    // Languages
    'language': 'Language',
    'english': 'English',
    'arabic': 'العربية',
    'spanish': 'Español',
    'french': 'Français',
    'hindi': 'हिंदी',
    'german': 'Deutsch',
    'portuguese': 'Português',
    'chinese': '中文',

    // Market Overview
    'real.time.market.data': 'Real-time market data and trends',
    'top.cryptocurrencies': 'Top Cryptocurrencies',
    'volume': 'Vol',
    
    // Bots
    'manage.monitor.bots': 'Manage and monitor your trading bots',
    'profit': 'Profit',
    'roi': 'ROI',
    'trades': 'Trades',
    'created': 'Created',
    'active': 'Active',
    'paused': 'Paused',
    'start': 'Start',
    'pause': 'Pause',
    'error': 'Error',
    'total.bots': 'Total Bots',
    
    // Bot Templates
    'preconfigured.bot.strategies': 'Pre-configured bot strategies ready to deploy',
    'use.template': 'Use Template',
    
    // Manual Trading
    'execute.trades.manually': 'Execute trades manually with real-time market data',
    'trading.chart': 'Trading Chart',
    'tradingview.chart.placeholder': 'TradingView Chart Placeholder',
    'place.order': 'Place Order',
    'buy': 'Buy',
    'sell': 'Sell',
    'order.type': 'Order Type',
    'select.order.type': 'Select order type',
    'market': 'Market',
    'limit': 'Limit',
    'stop': 'Stop',
    'price': 'Price',
    'amount': 'Amount',
    'order.book': 'Order Book',
    
    // Paper Trading
    'practice.trading.strategies': 'Practice trading strategies with virtual money',
    'virtual.balance': 'Virtual Balance',
    'paper.pnl': 'Paper P&L',
    'paper.trades': 'Paper Trades',
    'paper.trading.history': 'Paper Trading History',
    'closed': 'Closed',
    'open': 'Open',
    'start.new.paper.trading': 'Start New Paper Trading Session',
    'reset.virtual.balance': 'Reset Virtual Balance & Start Fresh',
    
    // Live Charts
    'realtime.trading.charts': 'Real-time trading charts with technical indicators',
    'advanced.tradingview.chart': 'Advanced TradingView Chart Integration',
    
    // Bot Performance
    'detailed.performance.metrics': 'Detailed performance metrics for all your trading bots',

    // Markets module
    'market.scanner': 'Market Scanner',
    'scan.markets.opportunities': 'Scan markets for trading opportunities with technical analysis',
    'scan.results': 'Scan Results',
    'strong.buy': 'STRONG BUY',
    'buy': 'BUY',
    'hold': 'HOLD',
    'sell': 'SELL',
    'vol': 'Vol',
    
    // Exchange API module
    'connect.manage.exchanges': 'Connect and manage your exchange accounts',
    'connected.exchanges': 'Connected Exchanges',
    'exchange.name': 'Exchange Name',
    'api.status': 'API Status',
    'last.sync': 'Last Sync',
    'actions': 'Actions',
    'connected': 'Connected',
    'disconnected': 'Disconnected',
    'configure': 'Configure',
    'disconnect': 'Disconnect',
    'add.new.exchange': 'Add New Exchange',
    'select.exchange': 'Select Exchange',
    'api.key': 'API Key',
    'api.secret': 'API Secret',
    'passphrase': 'Passphrase',
    'sandbox.mode': 'Sandbox Mode',
    'test.connection': 'Test Connection',
    'save.configuration': 'Save Configuration',
    
    // Alerts module
    'create.manage.alerts': 'Create and manage price alerts and notifications',
    'active.alerts': 'Active Alerts',
    'asset': 'Asset',
    'condition': 'Condition',
    'target.price': 'Target Price',
    'status': 'Status',
    'edit': 'Edit',
    'delete': 'Delete',
    'above': 'Above',
    'below': 'Below',
    'create.new.alert': 'Create New Alert',
    'select.asset': 'Select asset',
    'select.condition': 'Select condition',
    'enter.target.price': 'Enter target price',
    'notification.method': 'Notification Method',
    'email': 'Email',
    'push': 'Push',
    'webhook': 'Webhook',
    
    // Strategy module
    'build.test.strategies': 'Build and test your custom trading strategies',
    'strategy.name': 'Strategy Name',
    'strategy.description': 'Strategy Description',
    'indicators': 'Indicators',
    'conditions': 'Conditions',
    'add.indicator': 'Add Indicator',
    'add.condition': 'Add Condition',
    'rsi': 'RSI',
    'macd': 'MACD',
    'bollinger.bands': 'Bollinger Bands',
    'moving.average': 'Moving Average',
    'greater.than': 'Greater than',
    'less.than': 'Less than',
    'crosses.above': 'Crosses above',
    'crosses.below': 'Crosses below',
    'save.strategy': 'Save Strategy',
    'test.strategy': 'Test Strategy',
    'deploy.strategy': 'Deploy Strategy',
    
    // Settings module
    'settings': 'Settings',
    'manage.account.preferences': 'Manage your account and application preferences',
    'profile.information': 'Profile Information',
    'full.name': 'Full Name',
    'email.address': 'Email Address',
    'phone.number': 'Phone Number',
    'update.profile': 'Update Profile',
    'security.settings': 'Security Settings',
    'change.password': 'Change Password',
    'current.password': 'Current Password',
    'new.password': 'New Password',
    'confirm.password': 'Confirm Password',
    'update.password': 'Update Password',
    'two.factor.authentication': 'Two-Factor Authentication',
    'enable.2fa': 'Enable 2FA',
    'disable.2fa': 'Disable 2FA',
    'notification.preferences': 'Notification Preferences',
    'trade.notifications': 'Trade Notifications',
    'price.alerts.notifications': 'Price Alerts',
    'system.updates': 'System Updates',
    'marketing.emails': 'Marketing Emails',
    
    // Help module
    'get.help.support': 'Get help and support for using the platform',
    'frequently.asked.questions': 'Frequently Asked Questions',
    'how.to.create.bot': 'How do I create a trading bot?',
    'how.to.connect.exchange': 'How do I connect my exchange?',
    'how.to.set.alerts': 'How do I set up price alerts?',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'Support Hours: 24/7',
    'send.message': 'Send Message',
    'subject': 'Subject',
    'message': 'Message',
    'send': 'Send',
    'user.guides': 'User Guides',
    'getting.started.guide': 'Getting Started Guide',
    'advanced.trading.guide': 'Advanced Trading Guide',
    'api.documentation': 'API Documentation',
    'video.tutorials': 'Video Tutorials',
    'view.guide': 'View Guide',
    'watch.tutorial': 'Watch Tutorial',
  },
  ar: {
    // Header
    'search.placeholder': 'البحث في الأسواق والروبوتات...',
    'market.status': 'الأسواق مفتوحة',
    'user.name': 'جون دو',
    
    // Sidebar
    'app.name': 'كريبتو بوت برو',
    'dashboard': 'لوحة التحكم',
    'overview': 'نظرة عامة',
    'performance.summary': 'ملخص الأداء',
    'market.overview': 'نظرة عامة على السوق',
    
    'bots': 'الروبوتات',
    'create.new.bot': 'إنشاء روبوت جديد',
    'my.bots': 'روبوتاتي',
    'bot.performance': 'أداء الروبوت',
    'strategy.templates': 'قوالب الاستراتيجية',
    
    'trading': 'التداول',
    'manual.trading': 'التداول اليدوي',
    'signal.trading': 'تداول الإشارات',
    'paper.trading': 'التداول الورقي',
    
    'markets': 'الأسواق',
    'live.charts': 'الرسوم البيانية المباشرة',
    'market.scanner': 'ماسح السوق',
    'watchlist': 'قائمة المراقبة',
    'price.alerts': 'تنبيهات الأسعار',
    
    'exchanges.api': 'المنصات والواجهة البرمجية',
    'connect.exchange': 'ربط المنصة',
    'api.management': 'إدارة الواجهة البرمجية',
    'sync.balances': 'مزامنة الأرصدة',
    
    'alerts': 'التنبيهات',
    'create.alert': 'إنشاء تنبيه',
    'notification.settings': 'إعدادات الإشعارات',
    'alert.logs': 'سجلات التنبيهات',
    
    'strategy.builder': 'منشئ الاستراتيجية',
    'build.strategy': 'بناء استراتيجية',
    'saved.strategies': 'الاستراتيجيات المحفوظة',
    'backtesting': 'اختبار خلفي',
    'marketplace': 'السوق',
    
    'security.settings': 'الأمان والإعدادات',
    'profile.settings': 'إعدادات الملف الشخصي',
    'two.factor.auth': 'المصادقة الثنائية',
    'theme.settings': 'إعدادات السمة',
    'session.logs': 'سجلات الجلسة',
    
    'help': 'المساعدة',
    'documentation': 'التوثيق',
    'contact.support': 'اتصل بالدعم',
    'bug.reports': 'تقارير الأخطاء',
    'community': 'المجتمع',
    
    // Page content
    'welcome.back': 'مرحباً بعودتك! إليك نظرة عامة على نشاط تداول العملات المشفرة الخاص بك.',
    'total.pnl': 'إجمالي الربح والخسارة',
    'total.roi': 'إجمالي العائد على الاستثمار',
    'win.rate': 'معدل الفوز',
    'total.trades': 'إجمالي الصفقات',
    'create.bot': 'إنشاء روبوت',
    'bot.name': 'اسم الروبوت',
    'trading.pair': 'زوج التداول',
    'strategy.type': 'نوع الاستراتيجية',
    'investment.amount': 'مبلغ الاستثمار',
    'select.trading.pair': 'اختر زوج التداول',
    'select.strategy': 'اختر الاستراتيجية',
    'enter.amount.usdt': 'أدخل المبلغ بـ USDT',
    'enter.bot.name': 'أدخل اسم الروبوت',
    
    // Languages
    'language': 'اللغة',
    'english': 'English',
    'arabic': 'العربية',
    'spanish': 'Español',
    'french': 'Français',
    'hindi': 'हिंदी',
    'german': 'Deutsch',
    'portuguese': 'Português',
    'chinese': '中文',

    // Market Overview
    'real.time.market.data': 'بيانات السوق المباشرة والاتجاهات',
    'top.cryptocurrencies': 'أفضل العملات المشفرة',
    'volume': 'الحجم',
    
    // Bots
    'manage.monitor.bots': 'إدارة ومراقبة روبوتات التداول الخاصة بك',
    'profit': 'الربح',
    'roi': 'العائد على الاستثمار',
    'trades': 'الصفقات',
    'created': 'تم الإنشاء',
    'active': 'نشط',
    'paused': 'متوقف',
    'start': 'بدء',
    'pause': 'إيقاف',
    'error': 'خطأ',
    'total.bots': 'إجمالي الروبوتات',
    
    // Bot Templates
    'preconfigured.bot.strategies': 'استراتيجيات الروبوت المعدة مسبقاً جاهزة للنشر',
    'use.template': 'استخدام القالب',
    
    // Manual Trading
    'execute.trades.manually': 'تنفيذ الصفقات يدوياً مع بيانات السوق المباشرة',
    'trading.chart': 'مخطط التداول',
    'tradingview.chart.placeholder': 'عنصر نائب لمخطط TradingView',
    'place.order': 'وضع طلب',
    'buy': 'شراء',
    'sell': 'بيع',
    'order.type': 'نوع الطلب',
    'select.order.type': 'اختر نوع الطلب',
    'market': 'السوق',
    'limit': 'حد',
    'stop': 'توقف',
    'price': 'السعر',
    'amount': 'الكمية',
    'order.book': 'دفتر الطلبات',
    
    // Paper Trading
    'practice.trading.strategies': 'ممارسة استراتيجيات التداول بأموال افتراضية',
    'virtual.balance': 'الرصيد الافتراضي',
    'paper.pnl': 'ربح وخسارة ورقية',
    'paper.trades': 'صفقات ورقية',
    'paper.trading.history': 'تاريخ التداول الورقي',
    'closed': 'مغلق',
    'open': 'مفتوح',
    'start.new.paper.trading': 'بدء جلسة تداول ورقية جديدة',
    'reset.virtual.balance': 'إعادة تعيين الرصيد الافتراضي وبدء جديد',
    
    // Live Charts
    'realtime.trading.charts': 'مخططات التداول المباشرة مع المؤشرات الفنية',
    'advanced.tradingview.chart': 'تكامل مخطط TradingView المتقدم',
    
    // Bot Performance
    'detailed.performance.metrics': 'مقاييس الأداء التفصيلية لجميع روبوتات التداول الخاصة بك',

    // Markets module
    'scan.markets.opportunities': 'مسح الأسواق للعثور على فرص التداول مع التحليل الفني',
    'scan.results': 'نتائج المسح',
    'strong.buy': 'شراء قوي',
    'hold': 'احتفاظ',
    
    // Exchange API module
    'connect.manage.exchanges': 'ربط وإدارة حسابات المنصات الخاصة بك',
    'connected.exchanges': 'المنصات المتصلة',
    'exchange.name': 'اسم المنصة',
    'api.status': 'حالة الواجهة البرمجية',
    'last.sync': 'آخر مزامنة',
    'actions': 'الإجراءات',
    'connected': 'متصل',
    'disconnected': 'غير متصل',
    'configure': 'تكوين',
    'disconnect': 'قطع الاتصال',
    'add.new.exchange': 'إضافة منصة جديدة',
    'select.exchange': 'اختر المنصة',
    'api.key': 'مفتاح الواجهة البرمجية',
    'api.secret': 'سر الواجهة البرمجية',
    'passphrase': 'عبارة المرور',
    'sandbox.mode': 'وضع الاختبار',
    'test.connection': 'اختبار الاتصال',
    'save.configuration': 'حفظ التكوين',
    
    // Alerts module
    'create.manage.alerts': 'إنشاء وإدارة تنبيهات الأسعار والإشعارات',
    'active.alerts': 'التنبيهات النشطة',
    'above': 'أعلى من',
    'below': 'أقل من',
    'notification.method': 'طريقة الإشعار',
    
    // Strategy module
    'build.test.strategies': 'بناء واختبار استراتيجيات التداول المخصصة الخاصة بك',
    'strategy.name': 'اسم الاستراتيجية',
    'strategy.description': 'وصف الاستراتيجية',
    'indicators': 'المؤشرات',
    'conditions': 'الشروط',
    'add.indicator': 'إضافة مؤشر',
    'add.condition': 'إضافة شرط',
    'rsi': 'مؤشر القوة النسبية',
    'macd': 'ماكد',
    'bollinger.bands': 'نطاقات بولينجر',
    'moving.average': 'المتوسط المتحرك',
    'greater.than': 'أكبر من',
    'less.than': 'أقل من',
    'crosses.above': 'يعبر فوق',
    'crosses.below': 'يعبر تحت',
    'save.strategy': 'حفظ الاستراتيجية',
    'test.strategy': 'اختبار الاستراتيجية',
    'deploy.strategy': 'نشر الاستراتيجية',
    
    // Settings module
    'settings': 'الإعدادات',
    'manage.account.preferences': 'إدارة الحساب وتفضيلات التطبيق',
    'profile.information': 'معلومات الملف الشخصي',
    'full.name': 'الاسم الكامل',
    'email.address': 'عنوان البريد الإلكتروني',
    'phone.number': 'رقم الهاتف',
    'update.profile': 'تحديث الملف الشخصي',
    'security.settings': 'إعدادات الأمان',
    'change.password': 'تغيير كلمة المرور',
    'current.password': 'كلمة المرور الحالية',
    'new.password': 'كلمة المرور الجديدة',
    'confirm.password': 'تأكيد كلمة المرور',
    'update.password': 'تحديث كلمة المرور',
    'two.factor.authentication': 'المصادقة الثنائية',
    'enable.2fa': 'تفعيل المصادقة الثنائية',
    'disable.2fa': 'إلغاء المصادقة الثنائية',
    'notification.preferences': 'تفضيلات الإشعارات',
    'trade.notifications': 'إشعارات التداول',
    'price.alerts.notifications': 'تنبيهات الأسعار',
    'system.updates': 'تحديثات النظام',
    'marketing.emails': 'رسائل التسويق الإلكترونية',
    
    // Help module
    'get.help.support': 'الحصول على المساعدة والدعم لاستخدام المنصة',
    'frequently.asked.questions': 'الأسئلة الشائعة',
    'how.to.create.bot': 'كيف أقوم بإنشاء روبوت تداول؟',
    'how.to.connect.exchange': 'كيف أقوم بربط منصة التداول الخاصة بي؟',
    'how.to.set.alerts': 'كيف أقوم بإعداد تنبيهات الأسعار؟',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'ساعات الدعم: 24/7',
    'send.message': 'إرسال رسالة',
    'subject': 'الموضوع',
    'message': 'الرسالة',
    'send': 'إرسال',
    'user.guides': 'أدلة المستخدم',
    'getting.started.guide': 'دليل البدء',
    'advanced.trading.guide': 'دليل التداول المتقدم',
    'api.documentation': 'توثيق الواجهة البرمجية',
    'video.tutorials': 'دروس الفيديو',
    'view.guide': 'عرض الدليل',
    'watch.tutorial': 'مشاهدة الدرس',
  },
  es: {
    // Header
    'search.placeholder': 'Buscar mercados, bots...',
    'market.status': 'Mercados Abiertos',
    'user.name': 'Juan Pérez',
    
    // Sidebar
    'app.name': 'CryptoBot Pro',
    'dashboard': 'Panel de Control',
    'overview': 'Resumen',
    'performance.summary': 'Resumen de Rendimiento',
    'market.overview': 'Resumen del Mercado',
    
    'bots': 'Bots',
    'create.new.bot': 'Crear Nuevo Bot',
    'my.bots': 'Mis Bots',
    'bot.performance': 'Rendimiento del Bot',
    'strategy.templates': 'Plantillas de Estrategia',
    
    'trading': 'Trading',
    'manual.trading': 'Trading Manual',
    'signal.trading': 'Trading de Señales',
    'paper.trading': 'Trading en Papel',
    
    'markets': 'Mercados',
    'live.charts': 'Gráficos en Vivo',
    'market.scanner': 'Escáner de Mercado',
    'watchlist': 'Lista de Seguimiento',
    'price.alerts': 'Alertas de Precio',
    
    'exchanges.api': 'Exchanges y API',
    'connect.exchange': 'Conectar Exchange',
    'api.management': 'Gestión de API',
    'sync.balances': 'Sincronizar Saldos',
    
    'alerts': 'Alertas',
    'create.alert': 'Crear Alerta',
    'notification.settings': 'Configuración de Notificaciones',
    'alert.logs': 'Registros de Alertas',
    
    'strategy.builder': 'Constructor de Estrategias',
    'build.strategy': 'Construir Estrategia',
    'saved.strategies': 'Estrategias Guardadas',
    'backtesting': 'Backtesting',
    'marketplace': 'Mercado',
    
    'security.settings': 'Seguridad y Configuración',
    'profile.settings': 'Configuración del Perfil',
    'two.factor.auth': 'Autenticación de Dos Factores',
    'theme.settings': 'Configuración de Tema',
    'session.logs': 'Registros de Sesión',
    
    'help': 'Ayuda',
    'documentation': 'Documentación',
    'contact.support': 'Contactar Soporte',
    'bug.reports': 'Reportes de Errores',
    'community': 'Comunidad',
    
    // Page content
    'welcome.back': '¡Bienvenido de vuelta! Aquí tienes un resumen de tu actividad de trading de criptomonedas.',
    'total.pnl': 'P&L Total',
    'total.roi': 'ROI Total',
    'win.rate': 'Tasa de Ganancia',
    'total.trades': 'Operaciones Totales',
    'create.bot': 'Crear Bot',
    'bot.name': 'Nombre del Bot',
    'trading.pair': 'Par de Trading',
    'strategy.type': 'Tipo de Estrategia',
    'investment.amount': 'Cantidad de Inversión',
    'select.trading.pair': 'Seleccionar par de trading',
    'select.strategy': 'Seleccionar estrategia',
    'enter.amount.usdt': 'Ingresar cantidad en USDT',
    'enter.bot.name': 'Ingresar nombre del bot',
    
    // Languages
    'language': 'Idioma',
    'english': 'English',
    'arabic': 'العربية',
    'spanish': 'Español',
    'french': 'Français',
    'hindi': 'हिंदी',
    'german': 'Deutsch',
    'portuguese': 'Português',
    'chinese': '中文',

    // Market Overview
    'real.time.market.data': 'Datos de mercado y tendencias en tiempo real',
    'top.cryptocurrencies': 'Principales Criptomonedas',
    'volume': 'Vol',
    
    // Bots
    'manage.monitor.bots': 'Gestiona y monitorea tus bots de trading',
    'profit': 'Ganancia',
    'roi': 'ROI',
    'trades': 'Operaciones',
    'created': 'Creado',
    'active': 'Activo',
    'paused': 'Pausado',
    'start': 'Iniciar',
    'pause': 'Pausar',
    'error': 'Error',
    'total.bots': 'Total de Bots',
    
    // Bot Templates
    'preconfigured.bot.strategies': 'Estrategias de bot preconfiguradas listas para implementar',
    'use.template': 'Usar Plantilla',
    
    // Manual Trading
    'execute.trades.manually': 'Ejecuta operaciones manualmente con datos de mercado en tiempo real',
    'trading.chart': 'Gráfico de Trading',
    'tradingview.chart.placeholder': 'Marcador de Posición del Gráfico TradingView',
    'place.order': 'Colocar Orden',
    'buy': 'Comprar',
    'sell': 'Vender',
    'order.type': 'Tipo de Orden',
    'select.order.type': 'Seleccionar tipo de orden',
    'market': 'Mercado',
    'limit': 'Límite',
    'stop': 'Stop',
    'price': 'Precio',
    'amount': 'Cantidad',
    'order.book': 'Libro de Órdenes',
    
    // Paper Trading
    'practice.trading.strategies': 'Practica estrategias de trading con dinero virtual',
    'virtual.balance': 'Balance Virtual',
    'paper.pnl': 'P&L en Papel',
    'paper.trades': 'Operaciones en Papel',
    'paper.trading.history': 'Historial de Trading en Papel',
    'closed': 'Cerrado',
    'open': 'Abierto',
    'start.new.paper.trading': 'Iniciar Nueva Sesión de Trading en Papel',
    'reset.virtual.balance': 'Resetear Balance Virtual y Empezar de Nuevo',
    
    // Live Charts
    'realtime.trading.charts': 'Gráficos de trading en tiempo real con indicadores técnicos',
    'advanced.tradingview.chart': 'Integración Avanzada del Gráfico TradingView',
    
    // Bot Performance
    'detailed.performance.metrics': 'Métricas detalladas de rendimiento para todos tus bots de trading',

    // Markets module
    'scan.markets.opportunities': 'Escanear mercados en busca de oportunidades de trading con análisis técnico',
    'scan.results': 'Resultados del Escaneo',
    'strong.buy': 'COMPRA FUERTE',
    'hold': 'MANTENER',
    
    // Exchange API module
    'connect.manage.exchanges': 'Conectar y gestionar sus cuentas de exchange',
    'connected.exchanges': 'Exchanges Conectados',
    'exchange.name': 'Nombre del Exchange',
    'api.status': 'Estado de API',
    'last.sync': 'Última Sincronización',
    'actions': 'Acciones',
    'connected': 'Conectado',
    'disconnected': 'Desconectado',
    'configure': 'Configurar',
    'disconnect': 'Desconectar',
    'add.new.exchange': 'Agregar Nuevo Exchange',
    'select.exchange': 'Seleccionar Exchange',
    'api.key': 'Clave API',
    'api.secret': 'Secreto API',
    'passphrase': 'Frase de Paso',
    'sandbox.mode': 'Modo Sandbox',
    'test.connection': 'Probar Conexión',
    'save.configuration': 'Guardar Configuración',
    
    // Alerts module
    'create.manage.alerts': 'Crear y gestionar alertas de precios y notificaciones',
    'active.alerts': 'Alertas Activas',
    'above': 'Por encima',
    'below': 'Por debajo',
    'notification.method': 'Método de Notificación',
    
    // Strategy module
    'build.test.strategies': 'Construir y probar sus estrategias de trading personalizadas',
    'strategy.name': 'Nombre de la Estrategia',
    'strategy.description': 'Descripción de la Estrategia',
    'indicators': 'Indicadores',
    'conditions': 'Condiciones',
    'add.indicator': 'Agregar Indicador',
    'add.condition': 'Agregar Condición',
    'rsi': 'RSI',
    'macd': 'MACD',
    'bollinger.bands': 'Bandas de Bollinger',
    'moving.average': 'Media Móvil',
    'greater.than': 'Mayor que',
    'less.than': 'Menor que',
    'crosses.above': 'Cruza por encima',
    'crosses.below': 'Cruza por debajo',
    'save.strategy': 'Guardar Estrategia',
    'test.strategy': 'Probar Estrategia',
    'deploy.strategy': 'Implementar Estrategia',
    
    // Settings module
    'settings': 'Configuración',
    'manage.account.preferences': 'Gestionar cuenta y preferencias de la aplicación',
    'profile.information': 'Información del Perfil',
    'full.name': 'Nombre Completo',
    'email.address': 'Dirección de Email',
    'phone.number': 'Número de Teléfono',
    'update.profile': 'Actualizar Perfil',
    'security.settings': 'Configuración de Seguridad',
    'change.password': 'Cambiar Contraseña',
    'current.password': 'Contraseña Actual',
    'new.password': 'Nueva Contraseña',
    'confirm.password': 'Confirmar Contraseña',
    'update.password': 'Actualizar Contraseña',
    'two.factor.authentication': 'Autenticación de Dos Factores',
    'enable.2fa': 'Habilitar 2FA',
    'disable.2fa': 'Deshabilitar 2FA',
    'notification.preferences': 'Preferencias de Notificación',
    'trade.notifications': 'Notificaciones de Trading',
    'price.alerts.notifications': 'Alertas de Precios',
    'system.updates': 'Actualizaciones del Sistema',
    'marketing.emails': 'Emails de Marketing',
    
    // Help module
    'get.help.support': 'Obtener ayuda y soporte para usar la plataforma',
    'frequently.asked.questions': 'Preguntas Frecuentes',
    'how.to.create.bot': '¿Cómo creo un bot de trading?',
    'how.to.connect.exchange': '¿Cómo conecto mi exchange?',
    'how.to.set.alerts': '¿Cómo configuro alertas de precios?',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'Horarios de Soporte: 24/7',
    'send.message': 'Enviar Mensaje',
    'subject': 'Asunto',
    'message': 'Mensaje',
    'send': 'Enviar',
    'user.guides': 'Guías de Usuario',
    'getting.started.guide': 'Guía de Inicio',
    'advanced.trading.guide': 'Guía de Trading Avanzado',
    'api.documentation': 'Documentación de API',
    'video.tutorials': 'Tutoriales en Video',
    'view.guide': 'Ver Guía',
    'watch.tutorial': 'Ver Tutorial',
  },
  fr: {
    // Header
    'search.placeholder': 'Rechercher marchés, bots...',
    'market.status': 'Marchés Ouverts',
    'user.name': 'Jean Dupont',
    
    // Sidebar
    'app.name': 'CryptoBot Pro',
    'dashboard': 'Tableau de Bord',
    'overview': 'Aperçu',
    'performance.summary': 'Résumé des Performances',
    'market.overview': 'Aperçu du Marché',
    
    'bots': 'Bots',
    'create.new.bot': 'Créer Nouveau Bot',
    'my.bots': 'Mes Bots',
    'bot.performance': 'Performance du Bot',
    'strategy.templates': 'Modèles de Stratégie',
    
    'trading': 'Trading',
    'manual.trading': 'Trading Manuel',
    'signal.trading': 'Trading de Signaux',
    'paper.trading': 'Trading Papier',
    
    'markets': 'Marchés',
    'live.charts': 'Graphiques en Direct',
    'market.scanner': 'Scanner de Marché',
    'watchlist': 'Liste de Surveillance',
    'price.alerts': 'Alertes de Prix',
    
    'exchanges.api': 'Exchanges et API',
    'connect.exchange': 'Connecter Exchange',
    'api.management': 'Gestion API',
    'sync.balances': 'Synchroniser Soldes',
    
    'alerts': 'Alertes',
    'create.alert': 'Créer Alerte',
    'notification.settings': 'Paramètres de Notification',
    'alert.logs': 'Journaux d\'Alertes',
    
    'strategy.builder': 'Constructeur de Stratégie',
    'build.strategy': 'Construire Stratégie',
    'saved.strategies': 'Stratégies Sauvegardées',
    'backtesting': 'Backtesting',
    'marketplace': 'Marché',
    
    'security.settings': 'Sécurité et Paramètres',
    'profile.settings': 'Paramètres du Profil',
    'two.factor.auth': 'Authentification à Deux Facteurs',
    'theme.settings': 'Paramètres de Thème',
    'session.logs': 'Journaux de Session',
    
    'help': 'Aide',
    'documentation': 'Documentation',
    'contact.support': 'Contacter le Support',
    'bug.reports': 'Rapports de Bugs',
    'community': 'Communauté',
    
    // Page content
    'welcome.back': 'Bon retour ! Voici un aperçu de votre activité de trading crypto.',
    'total.pnl': 'P&L Total',
    'total.roi': 'ROI Total',
    'win.rate': 'Taux de Gain',
    'total.trades': 'Trades Totaux',
    'create.bot': 'Créer Bot',
    'bot.name': 'Nom du Bot',
    'trading.pair': 'Paire de Trading',
    'strategy.type': 'Type d\'Ordre',
    'investment.amount': 'Montant d\'Investissement',
    'select.trading.pair': 'Sélectionner paire de trading',
    'select.strategy': 'Sélectionner stratégie',
    'enter.amount.usdt': 'Entrer montant en USDT',
    'enter.bot.name': 'Entrer nom du bot',
    
    // Languages
    'language': 'Langue',
    'english': 'English',
    'arabic': 'العربية',
    'spanish': 'Español',
    'french': 'Français',
    'hindi': 'हिंदी',
    'german': 'Deutsch',
    'portuguese': 'Português',
    'chinese': '中文',

    // Market Overview
    'real.time.market.data': 'Données de marché et tendances en temps réel',
    'top.cryptocurrencies': 'Principales Cryptomonnaies',
    'volume': 'Vol',
    
    // Bots
    'manage.monitor.bots': 'Gérez et surveillez vos bots de trading',
    'profit': 'Profit',
    'roi': 'ROI',
    'trades': 'Trades',
    'created': 'Créé',
    'active': 'Actif',
    'paused': 'En Pause',
    'start': 'Démarrer',
    'pause': 'Pause',
    'error': 'Erreur',
    'total.bots': 'Total des Bots',
    
    // Bot Templates
    'preconfigured.bot.strategies': 'Stratégies de bot préconfigurées prêtes à déployer',
    'use.template': 'Utiliser le Modèle',
    
    // Manual Trading
    'execute.trades.manually': 'Exécutez des trades manuellement avec des données de marché en temps réel',
    'trading.chart': 'Graphique de Trading',
    'tradingview.chart.placeholder': 'Placeholder du Graphique TradingView',
    'place.order': 'Placer un Ordre',
    'buy': 'Acheter',
    'sell': 'Vendre',
    'order.type': 'Type d\'Ordre',
    'select.order.type': 'Sélectionner le type d\'ordre',
    'market': 'Marché',
    'limit': 'Limite',
    'stop': 'Stop',
    'price': 'Prix',
    'amount': 'Montant',
    'order.book': 'Carnet d\'Ordres',
    
    // Paper Trading
    'practice.trading.strategies': 'Pratiquez les stratégies de trading avec de l\'argent virtuel',
    'virtual.balance': 'Solde Virtuel',
    'paper.pnl': 'P&L Papier',
    'paper.trades': 'Trades Papier',
    'paper.trading.history': 'Historique du Trading Papier',
    'closed': 'Fermé',
    'open': 'Ouvert',
    'start.new.paper.trading': 'Démarrer une Nouvelle Session de Trading Papier',
    'reset.virtual.balance': 'Réinitialiser le Solde Virtuel et Recommencer',
    
    // Live Charts
    'realtime.trading.charts': 'Graphiques de trading en temps réel avec indicateurs techniques',
    'advanced.tradingview.chart': 'Intégration Avancée du Graphique TradingView',
    
    // Bot Performance
    'detailed.performance.metrics': 'Métriques de performance détaillées pour tous vos bots de trading',

    // Markets module
    'scan.markets.opportunities': 'Scanner les marchés pour des opportunités de trading avec analyse technique',
    'scan.results': 'Résultats du Scan',
    'strong.buy': 'ACHAT FORT',
    'hold': 'CONSERVER',
    
    // Exchange API module
    'connect.manage.exchanges': 'Connecter et gérer vos comptes d\'exchange',
    'connected.exchanges': 'Exchanges Connectés',
    'exchange.name': 'Nom de l\'Exchange',
    'api.status': 'Statut API',
    'last.sync': 'Dernière Sync',
    'actions': 'Actions',
    'connected': 'Connecté',
    'disconnected': 'Déconnecté',
    'configure': 'Configurer',
    'disconnect': 'Déconnecter',
    'add.new.exchange': 'Ajouter Nouvel Exchange',
    'select.exchange': 'Sélectionner Exchange',
    'api.key': 'Clé API',
    'api.secret': 'Secret API',
    'passphrase': 'Phrase de Passe',
    'sandbox.mode': 'Mode Sandbox',
    'test.connection': 'Tester Connexion',
    'save.configuration': 'Sauvegarder Configuration',
    
    // Alerts module
    'create.manage.alerts': 'Créer et gérer les alertes de prix et notifications',
    'active.alerts': 'Alertes Actives',
    'above': 'Au-dessus',
    'below': 'En-dessous',
    'notification.method': 'Méthode de Notification',
    
    // Strategy module
    'build.test.strategies': 'Construire et tester vos stratégies de trading personnalisées',
    'strategy.name': 'Nom de la Stratégie',
    'strategy.description': 'Description de la Stratégie',
    'indicators': 'Indicateurs',
    'conditions': 'Conditions',
    'add.indicator': 'Ajouter Indicateur',
    'add.condition': 'Ajouter Condition',
    'rsi': 'RSI',
    'macd': 'MACD',
    'bollinger.bands': 'Bandes de Bollinger',
    'moving.average': 'Moyenne Mobile',
    'greater.than': 'Supérieur à',
    'less.than': 'Inférieur à',
    'crosses.above': 'Croise au-dessus',
    'crosses.below': 'Croise en-dessous',
    'save.strategy': 'Sauvegarder Stratégie',
    'test.strategy': 'Tester Stratégie',
    'deploy.strategy': 'Déployer Stratégie',
    
    // Settings module
    'settings': 'Paramètres',
    'manage.account.preferences': 'Gérer le compte et les préférences de l\'application',
    'profile.information': 'Informations du Profil',
    'full.name': 'Nom Complet',
    'email.address': 'Adresse Email',
    'phone.number': 'Numéro de Téléphone',
    'update.profile': 'Mettre à Jour le Profil',
    'security.settings': 'Paramètres de Sécurité',
    'change.password': 'Changer le Mot de Passe',
    'current.password': 'Mot de Passe Actuel',
    'new.password': 'Nouveau Mot de Passe',
    'confirm.password': 'Confirmer le Mot de Passe',
    'update.password': 'Mettre à Jour le Mot de Passe',
    'two.factor.authentication': 'Authentification à Deux Facteurs',
    'enable.2fa': 'Activer 2FA',
    'disable.2fa': 'Désactiver 2FA',
    'notification.preferences': 'Préférences de Notification',
    'trade.notifications': 'Notifications de Trading',
    'price.alerts.notifications': 'Alertes de Prix',
    'system.updates': 'Mises à Jour Système',
    'marketing.emails': 'Emails Marketing',
    
    // Help module
    'get.help.support': 'Obtenir de l\'aide et du support pour utiliser la plateforme',
    'frequently.asked.questions': 'Questions Fréquemment Posées',
    'how.to.create.bot': 'Comment créer un bot de trading ?',
    'how.to.connect.exchange': 'Comment connecter mon exchange ?',
    'how.to.set.alerts': 'Comment configurer les alertes de prix ?',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'Heures de Support : 24/7',
    'send.message': 'Envoyer Message',
    'subject': 'Sujet',
    'message': 'Message',
    'send': 'Envoyer',
    'user.guides': 'Guides Utilisateur',
    'getting.started.guide': 'Guide de Démarrage',
    'advanced.trading.guide': 'Guide de Trading Avancé',
    'api.documentation': 'Documentation API',
    'video.tutorials': 'Tutoriels Vidéo',
    'view.guide': 'Voir le Guide',
    'watch.tutorial': 'Regarder le Tutoriel',
  },
  hi: {
    // Header
    'search.placeholder': 'मार्केट, बॉट्स खोजें...',
    'market.status': 'मार्केट खुला है',
    'user.name': 'जॉन डो',
    
    // Sidebar
    'app.name': 'क्रिप्टोबॉट प्रो',
    'dashboard': 'डैशबोर्ड',
    'overview': 'अवलोकन',
    'performance.summary': 'प्रदर्शन सारांश',
    'market.overview': 'मार्केट अवलोकन',
    
    'bots': 'बॉट्स',
    'create.new.bot': 'नया बॉट बनाएं',
    'my.bots': 'मेरे बॉट्स',
    'bot.performance': 'बॉट प्रदर्शन',
    'strategy.templates': 'रणनीति टेम्प्लेट',
    
    'trading': 'ट्रेडिंग',
    'manual.trading': 'मैन्युअल ट्रेडिंग',
    'signal.trading': 'सिग्नल ट्रेडिंग',
    'paper.trading': 'पेपर ट्रेडिंग',
    
    'markets': 'मार्केट्स',
    'live.charts': 'लाइव चार्ट्स',
    'market.scanner': 'मार्केट स्कैनर',
    'watchlist': 'वॉचलिस्ट',
    'price.alerts': 'प्राइस अलर्ट',
    
    'exchanges.api': 'एक्सचेंज और API',
    'connect.exchange': 'एक्सचेंज कनेक्ट करें',
    'api.management': 'API प्रबंधन',
    'sync.balances': 'बैलेंस सिंक करें',
    
    'alerts': 'अलर्ट्स',
    'create.alert': 'अलर्ट बनाएं',
    'notification.settings': 'नोटिफिकेशन सेटिंग्स',
    'alert.logs': 'अलर्ट लॉग्स',
    
    'strategy.builder': 'रणनीति निर्माता',
    'build.strategy': 'रणनीति बनाएं',
    'saved.strategies': 'सेव की गई रणनीतियां',
    'backtesting': 'बैकटेस्टिंग',
    'marketplace': 'मार्केटप्लेस',
    
    'security.settings': 'सुरक्षा और सेटिंग्स',
    'profile.settings': 'प्रोफाइल सेटिंग्स',
    'two.factor.auth': 'दो-कारक प्रमाणीकरण',
    'theme.settings': 'थीम सेटिंग्स',
    'session.logs': 'सेशन लॉग्स',
    
    'help': 'मदद',
    'documentation': 'दस्तावेज़ीकरण',
    'contact.support': 'सपोर्ट से संपर्क करें',
    'bug.reports': 'बग रिपोर्ट्स',
    'community': 'समुदाय',
    
    // Page content
    'welcome.back': 'वापसी पर स्वागत है! यहाँ आपकी क्रिप्टो ट्रेडिंग गतिविधि का अवलोकन है।',
    'total.pnl': 'कुल P&L',
    'total.roi': 'कुल ROI',
    'win.rate': 'जीत दर',
    'total.trades': 'कुल ट्रेड्स',
    'create.bot': 'बॉट बनाएं',
    'bot.name': 'बॉट का नाम',
    'trading.pair': 'ट्रेडिंग पेयर',
    'strategy.type': 'रणनीति का प्रकार',
    'investment.amount': 'निवेश राशि',
    'select.trading.pair': 'ट्रेडिंग पेयर चुनें',
    'select.strategy': 'रणनीति चुनें',
    'enter.amount.usdt': 'USDT में राशि दर्ज करें',
    'enter.bot.name': 'बॉट का नाम दर्ज करें',
    
    // Languages
    'language': 'भाषा',
    'english': 'English',
    'arabic': 'العربية',
    'spanish': 'Español',
    'french': 'Français',
    'hindi': 'हिंदी',
    'german': 'Deutsch',
    'portuguese': 'Português',
    'chinese': '中文',

    // Market Overview
    'real.time.market.data': 'वास्तविक समय बाजार डेटा और रुझान',
    'top.cryptocurrencies': 'शीर्ष क्रिप्टोकरेंसी',
    'volume': 'वॉल्यूम',
    
    // Bots
    'manage.monitor.bots': 'अपने ट्रेडिंग बॉट्स का प्रबंधन और निगरानी करें',
    'profit': 'लाभ',
    'roi': 'ROI',
    'trades': 'ट्रेड्स',
    'created': 'बनाया गया',
    'active': 'सक्रिय',
    'paused': 'रोका गया',
    'start': 'शुरू',
    'pause': 'रोकें',
    'error': 'त्रुटि',
    'total.bots': 'कुल बॉट्स',
    
    // Bot Templates
    'preconfigured.bot.strategies': 'पूर्व-कॉन्फ़िगर किए गए बॉट रणनीतियां तैनाती के लिए तैयार',
    'use.template': 'टेम्प्लेट का उपयोग करें',
    
    // Manual Trading
    'execute.trades.manually': 'वास्तविक समय बाजार डेटा के साथ मैन्युअल रूप से ट्रेड्स निष्पादित करें',
    'trading.chart': 'ट्रेडिंग चार्ट',
    'tradingview.chart.placeholder': 'TradingView चार्ट प्लेसहोल्डर',
    'place.order': 'ऑर्डर दें',
    'buy': 'खरीदें',
    'sell': 'बेचें',
    'order.type': 'ऑर्डर प्रकार',
    'select.order.type': 'ऑर्डर प्रकार चुनें',
    'market': 'मार्केट',
    'limit': 'लिमिट',
    'stop': 'स्टॉप',
    'price': 'कीमत',
    'amount': 'राशि',
    'order.book': 'ऑर्डर बुक',
    
    // Paper Trading
    'practice.trading.strategies': 'वर्चुअल पैसे से ट्रेडिंग रणनीतियों का अभ्यास करें',
    'virtual.balance': 'वर्चुअल बैलेंस',
    'paper.pnl': 'पेपर P&L',
    'paper.trades': 'पेपर ट्रेड्स',
    'paper.trading.history': 'पेपर ट्रेडिंग इतिहास',
    'closed': 'बंद',
    'open': 'खुला',
    'start.new.paper.trading': 'नया पेपर ट्रेडिंग सेशन शुरू करें',
    'reset.virtual.balance': 'वर्चुअल बैलेंस रीसेट करें और नया शुरू करें',
    
    // Live Charts
    'realtime.trading.charts': 'तकनीकी संकेतकों के साथ वास्तविक समय ट्रेडिंग चार्ट',
    'advanced.tradingview.chart': 'उन्नत TradingView चार्ट एकीकरण',
    
    // Bot Performance
    'detailed.performance.metrics': 'आपके सभी ट्रेडिंग बॉट्स के लिए विस्तृत प्रदर्शन मेट्रिक्स',

    // Markets module
    'scan.markets.opportunities': 'तकनीकी विश्लेषण के साथ ट्रेडिंग अवसरों के लिए बाजारों को स्कैन करें',
    'scan.results': 'स्कैन परिणाम',
    'strong.buy': 'मजबूत खरीदारी',
    'hold': 'होल्ड',
    
    // Exchange API module
    'connect.manage.exchanges': 'अपने एक्सचेंज खातों को कनेक्ट और प्रबंधित करें',
    'connected.exchanges': 'कनेक्टेड एक्सचेंज',
    'exchange.name': 'एक्सचेंज नाम',
    'api.status': 'API स्थिति',
    'last.sync': 'अंतिम सिंक',
    'actions': 'कार्य',
    'connected': 'कनेक्टेड',
    'disconnected': 'डिस्कनेक्टेड',
    'configure': 'कॉन्फ़िगर करें',
    'disconnect': 'डिस्कनेक्ट करें',
    'add.new.exchange': 'नया एक्सचेंज जोड़ें',
    'select.exchange': 'एक्सचेंज चुनें',
    'api.key': 'API कुंजी',
    'api.secret': 'API सीक्रेट',
    'passphrase': 'पासफ्रेज',
    'sandbox.mode': 'सैंडबॉक्स मोड',
    'test.connection': 'कनेक्शन टेस्ट करें',
    'save.configuration': 'कॉन्फ़िगरेशन सेव करें',
    
    // Alerts module
    'create.manage.alerts': 'प्राइस अलर्ट और नोटिफिकेशन बनाएं और प्रबंधित करें',
    'active.alerts': 'सक्रिय अलर्ट',
    'above': 'ऊपर',
    'below': 'नीचे',
    'notification.method': 'नोटिफिकेशन विधि',
    
    // Strategy module
    'build.test.strategies': 'अपनी कस्टम ट्रेडिंग रणनीतियों का निर्माण और परीक्षण करें',
    'strategy.name': 'रणनीति का नाम',
    'strategy.description': 'रणनीति विवरण',
    'indicators': 'संकेतक',
    'conditions': 'शर्तें',
    'add.indicator': 'संकेतक जोड़ें',
    'add.condition': 'शर्त जोड़ें',
    'rsi': 'RSI',
    'macd': 'MACD',
    'bollinger.bands': 'बोलिंगर बैंड',
    'moving.average': 'मूविंग एवरेज',
    'greater.than': 'से अधिक',
    'less.than': 'से कम',
    'crosses.above': 'ऊपर पार करता है',
    'crosses.below': 'नीचे पार करता है',
    'save.strategy': 'रणनीति सेव करें',
    'test.strategy': 'रणनीति टेस्ट करें',
    'deploy.strategy': 'रणनीति डिप्लॉय करें',
    
    // Settings module
    'settings': 'सेटिंग्स',
    'manage.account.preferences': 'अपने खाते और एप्लिकेशन प्राथमिकताओं का प्रबंधन करें',
    'profile.information': 'प्रोफाइल जानकारी',
    'full.name': 'पूरा नाम',
    'email.address': 'ईमेल पता',
    'phone.number': 'फोन नंबर',
    'update.profile': 'प्रोफाइल अपडेट करें',
    'security.settings': 'सुरक्षा सेटिंग्स',
    'change.password': 'पासवर्ड बदलें',
    'current.password': 'वर्तमान पासवर्ड',
    'new.password': 'नया पासवर्ड',
    'confirm.password': 'पासवर्ड कन्फर्म करें',
    'update.password': 'पासवर्ड अपडेट करें',
    'two.factor.authentication': 'दो-कारक प्रमाणीकरण',
    'enable.2fa': '2FA सक्षम करें',
    'disable.2fa': '2FA अक्षम करें',
    'notification.preferences': 'नोटिफिकेशन प्राथमिकताएं',
    'trade.notifications': 'ट्रेड नोटिफिकेशन',
    'price.alerts.notifications': 'प्राइस अलर्ट',
    'system.updates': 'सिस्टम अपडेट',
    'marketing.emails': 'मार्केटिंग ईमेल',
    
    // Help module
    'get.help.support': 'प्लेटफॉर्म का उपयोग करने के लिए सहायता और समर्थन प्राप्त करें',
    'frequently.asked.questions': 'अक्सर पूछे जाने वाले प्रश्न',
    'how.to.create.bot': 'मैं ट्रेडिंग बॉट कैसे बनाऊं?',
    'how.to.connect.exchange': 'मैं अपना एक्सचेंज कैसे कनेक्ट करूं?',
    'how.to.set.alerts': 'मैं प्राइस अलर्ट कैसे सेट करूं?',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'सपोर्ट घंटे: 24/7',
    'send.message': 'संदेश भेजें',
    'subject': 'विषय',
    'message': 'संदेश',
    'send': 'भेजें',
    'user.guides': 'उपयोगकर्ता गाइड',
    'getting.started.guide': 'शुरुआती गाइड',
    'advanced.trading.guide': 'उन्नत ट्रेडिंग गाइड',
    'api.documentation': 'API दस्तावेज़',
    'video.tutorials': 'वीडियो ट्यूटोरियल',
    'view.guide': 'गाइड देखें',
    'watch.tutorial': 'ट्यूटोरियल देखें',
  },
  de: {
    // Header
    'search.placeholder': 'Märkte, Bots suchen...',
    'market.status': 'Märkte Geöffnet',
    'user.name': 'Hans Mueller',
    
    // Sidebar
    'app.name': 'CryptoBot Pro',
    'dashboard': 'Dashboard',
    'overview': 'Übersicht',
    'performance.summary': 'Leistungsübersicht',
    'market.overview': 'Marktübersicht',
    
    'bots': 'Bots',
    'create.new.bot': 'Neuen Bot Erstellen',
    'my.bots': 'Meine Bots',
    'bot.performance': 'Bot-Leistung',
    'strategy.templates': 'Strategie-Vorlagen',
    
    'trading': 'Trading',
    'manual.trading': 'Manuelles Trading',
    'signal.trading': 'Signal Trading',
    'paper.trading': 'Paper Trading',
    
    'markets': 'Märkte',
    'live.charts': 'Live-Charts',
    'market.scanner': 'Markt-Scanner',
    'watchlist': 'Watchlist',
    'price.alerts': 'Preisalarme',
    
    'exchanges.api': 'Börsen & API',
    'connect.exchange': 'Börse Verbinden',
    'api.management': 'API-Verwaltung',
    'sync.balances': 'Salden Synchronisieren',
    
    'alerts': 'Alarme',
    'create.alert': 'Alarm Erstellen',
    'notification.settings': 'Benachrichtigungseinstellungen',
    'alert.logs': 'Alarm-Protokolle',
    
    'strategy.builder': 'Strategie-Builder',
    'build.strategy': 'Strategie Erstellen',
    'saved.strategies': 'Gespeicherte Strategien',
    'backtesting': 'Backtesting',
    'marketplace': 'Marktplatz',
    
    'security.settings': 'Sicherheit & Einstellungen',
    'profile.settings': 'Profil-Einstellungen',
    'two.factor.auth': 'Zwei-Faktor-Authentifizierung',
    'theme.settings': 'Theme-Einstellungen',
    'session.logs': 'Sitzungsprotokolle',
    
    'help': 'Hilfe',
    'documentation': 'Dokumentation',
    'contact.support': 'Support Kontaktieren',
    'bug.reports': 'Fehlerberichte',
    'community': 'Community',
    
    // Page content
    'welcome.back': 'Willkommen zurück! Hier ist eine Übersicht Ihrer Krypto-Trading-Aktivitäten.',
    'total.pnl': 'Gesamt P&L',
    'total.roi': 'Gesamt ROI',
    'win.rate': 'Gewinnrate',
    'total.trades': 'Gesamt Trades',
    'create.bot': 'Bot Erstellen',
    'bot.name': 'Bot-Name',
    'trading.pair': 'Trading-Paar',
    'strategy.type': 'Strategie-Typ',
    'investment.amount': 'Investitionsbetrag',
    'select.trading.pair': 'Trading-Paar auswählen',
    'select.strategy': 'Strategie auswählen',
    'enter.amount.usdt': 'Betrag in USDT eingeben',
    'enter.bot.name': 'Bot-Namen eingeben',
    
    // Languages
    'language': 'Sprache',
    'english': 'English',
    'arabic': 'العربية',
    'spanish': 'Español',
    'french': 'Français',
    'hindi': 'हिंदी',
    'german': 'Deutsch',
    'portuguese': 'Português',
    'chinese': '中文',

    // Market Overview
    'real.time.market.data': 'Echtzeit-Marktdaten und Trends',
    'top.cryptocurrencies': 'Top Kryptowährungen',
    'volume': 'Vol',
    
    // Bots
    'manage.monitor.bots': 'Verwalten und überwachen Sie Ihre Trading-Bots',
    'profit': 'Gewinn',
    'roi': 'ROI',
    'trades': 'Trades',
    'created': 'Erstellt',
    'active': 'Aktiv',
    'paused': 'Pausiert',
    'start': 'Starten',
    'pause': 'Pausieren',
    'error': 'Fehler',
    'total.bots': 'Gesamt Bots',
    
    // Bot Templates
    'preconfigured.bot.strategies': 'Vorkonfigurierte Bot-Strategien bereit zum Einsatz',
    'use.template': 'Vorlage Verwenden',
    
    // Manual Trading
    'execute.trades.manually': 'Führen Sie Trades manuell mit Echtzeit-Marktdaten aus',
    'trading.chart': 'Trading-Chart',
    'tradingview.chart.placeholder': 'TradingView Chart Platzhalter',
    'place.order': 'Order Platzieren',
    'buy': 'Kaufen',
    'sell': 'Verkaufen',
    'order.type': 'Order-Typ',
    'select.order.type': 'Order-Typ auswählen',
    'market': 'Markt',
    'limit': 'Limit',
    'stop': 'Stop',
    'price': 'Preis',
    'amount': 'Betrag',
    'order.book': 'Orderbuch',
    
    // Paper Trading
    'practice.trading.strategies': 'Üben Sie Trading-Strategien mit virtuellem Geld',
    'virtual.balance': 'Virtuelles Guthaben',
    'paper.pnl': 'Paper P&L',
    'paper.trades': 'Paper Trades',
    'paper.trading.history': 'Paper Trading Verlauf',
    'closed': 'Geschlossen',
    'open': 'Offen',
    'start.new.paper.trading': 'Neue Paper Trading Sitzung Starten',
    'reset.virtual.balance': 'Virtuelles Guthaben Zurücksetzen und Neu Beginnen',
    
    // Live Charts
    'realtime.trading.charts': 'Echtzeit-Trading-Charts mit technischen Indikatoren',
    'advanced.tradingview.chart': 'Erweiterte TradingView Chart Integration',
    
    // Bot Performance
    'detailed.performance.metrics': 'Detaillierte Leistungsmetriken für alle Ihre Trading-Bots',

    // Markets module
    'scan.markets.opportunities': 'Märkte nach Trading-Gelegenheiten mit technischer Analyse scannen',
    'scan.results': 'Scan-Ergebnisse',
    'strong.buy': 'STARKER KAUF',
    'hold': 'HALTEN',
    
    // Exchange API module
    'connect.manage.exchanges': 'Verbinden und verwalten Sie Ihre Börsenkonten',
    'connected.exchanges': 'Verbundene Börsen',
    'exchange.name': 'Börsenname',
    'api.status': 'API-Status',
    'last.sync': 'Letzte Sync',
    'actions': 'Aktionen',
    'connected': 'Verbunden',
    'disconnected': 'Getrennt',
    'configure': 'Konfigurieren',
    'disconnect': 'Trennen',
    'add.new.exchange': 'Neue Börse Hinzufügen',
    'select.exchange': 'Börse Auswählen',
    'api.key': 'API-Schlüssel',
    'api.secret': 'API-Geheimnis',
    'passphrase': 'Passphrase',
    'sandbox.mode': 'Sandbox-Modus',
    'test.connection': 'Verbindung Testen',
    'save.configuration': 'Konfiguration Speichern',
    
    // Alerts module
    'create.manage.alerts': 'Preisalarme und Benachrichtigungen erstellen und verwalten',
    'active.alerts': 'Aktive Alarme',
    'above': 'Über',
    'below': 'Unter',
    'notification.method': 'Benachrichtigungsmethode',
    
    // Strategy module
    'build.test.strategies': 'Erstellen und testen Sie Ihre benutzerdefinierten Trading-Strategien',
    'strategy.name': 'Strategie-Name',
    'strategy.description': 'Strategie-Beschreibung',
    'indicators': 'Indikatoren',
    'conditions': 'Bedingungen',
    'add.indicator': 'Indikator Hinzufügen',
    'add.condition': 'Bedingung Hinzufügen',
    'rsi': 'RSI',
    'macd': 'MACD',
    'bollinger.bands': 'Bollinger-Bänder',
    'moving.average': 'Gleitender Durchschnitt',
    'greater.than': 'Größer als',
    'less.than': 'Kleiner als',
    'crosses.above': 'Kreuzt über',
    'crosses.below': 'Kreuzt unter',
    'save.strategy': 'Strategie Speichern',
    'test.strategy': 'Strategie Testen',
    'deploy.strategy': 'Strategie Bereitstellen',
    
    // Settings module
    'settings': 'Einstellungen',
    'manage.account.preferences': 'Verwalten Sie Konto- und Anwendungseinstellungen',
    'profile.information': 'Profil-Informationen',
    'full.name': 'Vollständiger Name',
    'email.address': 'E-Mail-Adresse',
    'phone.number': 'Telefonnummer',
    'update.profile': 'Profil Aktualisieren',
    'security.settings': 'Sicherheitseinstellungen',
    'change.password': 'Passwort Ändern',
    'current.password': 'Aktuelles Passwort',
    'new.password': 'Neues Passwort',
    'confirm.password': 'Passwort Bestätigen',
    'update.password': 'Passwort Aktualisieren',
    'two.factor.authentication': 'Zwei-Faktor-Authentifizierung',
    'enable.2fa': '2FA Aktivieren',
    'disable.2fa': '2FA Deaktivieren',
    'notification.preferences': 'Benachrichtigungseinstellungen',
    'trade.notifications': 'Trading-Benachrichtigungen',
    'price.alerts.notifications': 'Preisalarme',
    'system.updates': 'System-Updates',
    'marketing.emails': 'Marketing-E-Mails',
    
    // Help module
    'get.help.support': 'Hilfe und Support für die Nutzung der Plattform erhalten',
    'frequently.asked.questions': 'Häufig Gestellte Fragen',
    'how.to.create.bot': 'Wie erstelle ich einen Trading-Bot?',
    'how.to.connect.exchange': 'Wie verbinde ich meine Börse?',
    'how.to.set.alerts': 'Wie richte ich Preisalarme ein?',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'Support-Zeiten: 24/7',
    'send.message': 'Nachricht Senden',
    'subject': 'Betreff',
    'message': 'Nachricht',
    'send': 'Senden',
    'user.guides': 'Benutzerhandbücher',
    'getting.started.guide': 'Erste Schritte Anleitung',
    'advanced.trading.guide': 'Erweiterte Trading-Anleitung',
    'api.documentation': 'API-Dokumentation',
    'video.tutorials': 'Video-Tutorials',
    'view.guide': 'Anleitung Anzeigen',
    'watch.tutorial': 'Tutorial Ansehen',
  },
  pt: {
    // Header
    'search.placeholder': 'Pesquisar mercados, bots...',
    'market.status': 'Mercados Abertos',
    'user.name': 'João Silva',
    
    // Sidebar
    'app.name': 'CryptoBot Pro',
    'dashboard': 'Painel',
    'overview': 'Visão Geral',
    'performance.summary': 'Resumo de Performance',
    'market.overview': 'Visão Geral do Mercado',
    
    'bots': 'Bots',
    'create.new.bot': 'Criar Novo Bot',
    'my.bots': 'Meus Bots',
    'bot.performance': 'Performance do Bot',
    'strategy.templates': 'Modelos de Estratégia',
    
    'trading': 'Trading',
    'manual.trading': 'Trading Manual',
    'signal.trading': 'Trading de Sinais',
    'paper.trading': 'Paper Trading',
    
    'markets': 'Mercados',
    'live.charts': 'Gráficos ao Vivo',
    'market.scanner': 'Scanner de Mercado',
    'watchlist': 'Lista de Observação',
    'price.alerts': 'Alertas de Preço',
    
    'exchanges.api': 'Exchanges e API',
    'connect.exchange': 'Conectar Exchange',
    'api.management': 'Gerenciamento de API',
    'sync.balances': 'Sincronizar Saldos',
    
    'alerts': 'Alertas',
    'create.alert': 'Criar Alerta',
    'notification.settings': 'Configurações de Notificação',
    'alert.logs': 'Logs de Alertas',
    
    'strategy.builder': 'Construtor de Estratégia',
    'build.strategy': 'Construir Estratégia',
    'saved.strategies': 'Estratégias Salvas',
    'backtesting': 'Backtesting',
    'marketplace': 'Marketplace',
    
    'security.settings': 'Segurança e Configurações',
    'profile.settings': 'Configurações do Perfil',
    'two.factor.auth': 'Autenticação de Dois Fatores',
    'theme.settings': 'Configurações de Tema',
    'session.logs': 'Logs de Sessão',
    
    'help': 'Ajuda',
    'documentation': 'Documentação',
    'contact.support': 'Contatar Suporte',
    'bug.reports': 'Relatórios de Bugs',
    'community': 'Comunidade',
    
    // Page content
    'welcome.back': 'Bem-vindo de volta! Aqui está uma visão geral da sua atividade de trading de criptomoedas.',
    'total.pnl': 'P&L Total',
    'total.roi': 'ROI Total',
    'win.rate': 'Taxa de Vitória',
    'total.trades': 'Trades Totais',
    'create.bot': 'Criar Bot',
    'bot.name': 'Nome do Bot',
    'trading.pair': 'Par de Trading',
    'strategy.type': 'Tipo de Estratégia',
    'investment.amount': 'Valor do Investimento',
    'select.trading.pair': 'Selecionar par de trading',
    'select.strategy': 'Selecionar estratégia',
    'enter.amount.usdt': 'Inserir valor em USDT',
    'enter.bot.name': 'Inserir nome do bot',
    
    // Languages
    'language': 'Idioma',
    'english': 'English',
    'arabic': 'العربية',
    'spanish': 'Español',
    'french': 'Français',
    'hindi': 'हिंदी',
    'german': 'Deutsch',
    'portuguese': 'Português',
    'chinese': '中文',

    // Market Overview
    'real.time.market.data': 'Dados de mercado e tendências em tempo real',
    'top.cryptocurrencies': 'Principais Criptomoedas',
    'volume': 'Vol',
    
    // Bots
    'manage.monitor.bots': 'Gerencie e monitore seus bots de trading',
    'profit': 'Lucro',
    'roi': 'ROI',
    'trades': 'Trades',
    'created': 'Criado',
    'active': 'Ativo',
    'paused': 'Pausado',
    'start': 'Iniciar',
    'pause': 'Pausar',
    'error': 'Erro',
    'total.bots': 'Total de Bots',
    
    // Bot Templates
    'preconfigured.bot.strategies': 'Estratégias de bot pré-configuradas prontas para implementar',
    'use.template': 'Usar Template',
    
    // Manual Trading
    'execute.trades.manually': 'Execute trades manualmente com dados de mercado em tempo real',
    'trading.chart': 'Gráfico de Trading',
    'tradingview.chart.placeholder': 'Placeholder do Gráfico TradingView',
    'place.order': 'Colocar Ordem',
    'buy': 'Comprar',
    'sell': 'Vender',
    'order.type': 'Tipo de Ordem',
    'select.order.type': 'Selecionar tipo de ordem',
    'market': 'Mercado',
    'limit': 'Limite',
    'stop': 'Stop',
    'price': 'Preço',
    'amount': 'Quantidade',
    'order.book': 'Livro de Ordens',
    
    // Paper Trading
    'practice.trading.strategies': 'Pratique estratégias de trading com dinheiro virtual',
    'virtual.balance': 'Saldo Virtual',
    'paper.pnl': 'P&L Papel',
    'paper.trades': 'Trades Papel',
    'paper.trading.history': 'Histórico de Trading Papel',
    'closed': 'Fechado',
    'open': 'Aberto',
    'start.new.paper.trading': 'Iniciar Nova Sessão de Paper Trading',
    'reset.virtual.balance': 'Redefinir Saldo Virtual e Começar do Zero',
    
    // Live Charts
    'realtime.trading.charts': 'Gráficos de trading em tempo real com indicadores técnicos',
    'advanced.tradingview.chart': 'Integração Avançada do Gráfico TradingView',
    
    // Bot Performance
    'detailed.performance.metrics': 'Métricas detalhadas de performance para todos os seus bots de trading',

    // Markets module
    'scan.markets.opportunities': 'Escanear mercados por oportunidades de trading com análise técnica',
    'scan.results': 'Resultados do Scan',
    'strong.buy': 'COMPRA FORTE',
    'hold': 'MANTER',
    
    // Exchange API module
    'connect.manage.exchanges': 'Conectar e gerenciar suas contas de exchange',
    'connected.exchanges': 'Exchanges Conectadas',
    'exchange.name': 'Nome da Exchange',
    'api.status': 'Status da API',
    'last.sync': 'Última Sincronização',
    'actions': 'Ações',
    'connected': 'Conectado',
    'disconnected': 'Desconectado',
    'configure': 'Configurar',
    'disconnect': 'Desconectar',
    'add.new.exchange': 'Adicionar Nova Exchange',
    'select.exchange': 'Selecionar Exchange',
    'api.key': 'Chave API',
    'api.secret': 'Segredo API',
    'passphrase': 'Frase-senha',
    'sandbox.mode': 'Modo Sandbox',
    'test.connection': 'Testar Conexão',
    'save.configuration': 'Salvar Configuração',
    
    // Alerts module
    'create.manage.alerts': 'Criar e gerenciar alertas de preço e notificações',
    'active.alerts': 'Alertas Ativos',
    'above': 'Acima',
    'below': 'Abaixo',
    'notification.method': 'Método de Notificação',
    
    // Strategy module
    'build.test.strategies': 'Construir e testar suas estratégias de trading personalizadas',
    'strategy.name': 'Nome da Estratégia',
    'strategy.description': 'Descrição da Estratégia',
    'indicators': 'Indicadores',
    'conditions': 'Condições',
    'add.indicator': 'Adicionar Indicador',
    'add.condition': 'Adicionar Condição',
    'rsi': 'RSI',
    'macd': 'MACD',
    'bollinger.bands': 'Bandas de Bollinger',
    'moving.average': 'Média Móvel',
    'greater.than': 'Maior que',
    'less.than': 'Menor que',
    'crosses.above': 'Cruza acima',
    'crosses.below': 'Cruza abaixo',
    'save.strategy': 'Salvar Estratégia',
    'test.strategy': 'Testar Estratégia',
    'deploy.strategy': 'Implementar Estratégia',
    
    // Settings module
    'settings': 'Configurações',
    'manage.account.preferences': 'Gerenciar conta e preferências do aplicativo',
    'profile.information': 'Informações do Perfil',
    'full.name': 'Nome Completo',
    'email.address': 'Endereço de Email',
    'phone.number': 'Número de Telefone',
    'update.profile': 'Atualizar Perfil',
    'security.settings': 'Configurações de Segurança',
    'change.password': 'Alterar Senha',
    'current.password': 'Senha Atual',
    'new.password': 'Nova Senha',
    'confirm.password': 'Confirmar Senha',
    'update.password': 'Atualizar Senha',
    'two.factor.authentication': 'Autenticação de Dois Fatores',
    'enable.2fa': 'Ativar 2FA',
    'disable.2fa': 'Desativar 2FA',
    'notification.preferences': 'Preferências de Notificação',
    'trade.notifications': 'Notificações de Trading',
    'price.alerts.notifications': 'Alertas de Preço',
    'system.updates': 'Atualizações do Sistema',
    'marketing.emails': 'Emails de Marketing',
    
    // Help module
    'get.help.support': 'Obter ajuda e suporte para usar a plataforma',
    'frequently.asked.questions': 'Perguntas Frequentes',
    'how.to.create.bot': 'Como criar um bot de trading?',
    'how.to.connect.exchange': 'Como conectar minha exchange?',
    'how.to.set.alerts': 'Como configurar alertas de preço?',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'Horário de Suporte: 24/7',
    'send.message': 'Enviar Mensagem',
    'subject': 'Assunto',
    'message': 'Mensagem',
    'send': 'Enviar',
    'user.guides': 'Guias do Usuário',
    'getting.started.guide': 'Guia de Início',
    'advanced.trading.guide': 'Guia de Trading Avançado',
    'api.documentation': 'Documentação da API',
    'video.tutorials': 'Tutoriais em Vídeo',
    'view.guide': 'Ver Guia',
    'watch.tutorial': 'Assistir Tutorial',
  },
  zh: {
    // Header
    'search.placeholder': '搜索市场、机器人...',
    'market.status': '市场开放',
    'user.name': '张三',
    
    // Sidebar
    'app.name': '加密机器人专业版',
    'dashboard': '仪表板',
    'overview': '概览',
    'performance.summary': '绩效摘要',
    'market.overview': '市场概览',
    
    'bots': '机器人',
    'create.new.bot': '创建新机器人',
    'my.bots': '我的机器人',
    'bot.performance': '机器人性能',
    'strategy.templates': '策略模板',
    
    'trading': '交易',
    'manual.trading': '手动交易',
    'signal.trading': '信号交易',
    'paper.trading': '模拟交易',
    
    'markets': '市场',
    'live.charts': '实时图表',
    'market.scanner': '市场扫描器',
    'watchlist': '观察列表',
    'price.alerts': '价格提醒',
    
    'exchanges.api': '交易所和API',
    'connect.exchange': '连接交易所',
    'api.management': 'API管理',
    'sync.balances': '同步余额',
    
    'alerts': '提醒',
    'create.alert': '创建提醒',
    'notification.settings': '通知设置',
    'alert.logs': '提醒日志',
    
    'strategy.builder': '策略构建器',
    'build.strategy': '构建策略',
    'saved.strategies': '已保存策略',
    'backtesting': '回测',
    'marketplace': '市场',
    
    'security.settings': '安全和设置',
    'profile.settings': '个人资料设置',
    'two.factor.auth': '双重身份验证',
    'theme.settings': '主题设置',
    'session.logs': '会话日志',
    
    'help': '帮助',
    'documentation': '文档',
    'contact.support': '联系支持',
    'bug.reports': '错误报告',
    'community': '社区',
    
    // Page content
    'welcome.back': '欢迎回来！这是您的加密货币交易活动概览。',
    'total.pnl': '总盈亏',
    'total.roi': '总投资回报率',
    'win.rate': '胜率',
    'total.trades': '总交易次数',
    'create.bot': '创建机器人',
    'bot.name': '机器人名称',
    'trading.pair': '交易对',
    'strategy.type': '策略类型',
    'investment.amount': '投资金额',
    'select.trading.pair': '选择交易对',
    'select.strategy': '选择策略',
    'enter.amount.usdt': '输入USDT金额',
    'enter.bot.name': '输入机器人名称',
    
    // Languages
    'language': '语言',
    'english': 'English',
    'arabic': 'العربية',
    'spanish': 'Español',
    'french': 'Français',
    'hindi': 'हिंदी',
    'german': 'Deutsch',
    'portuguese': 'Português',
    'chinese': '中文',

    // Market Overview
    'real.time.market.data': '实时市场数据和趋势',
    'top.cryptocurrencies': '顶级加密货币',
    'volume': '成交量',
    
    // Bots
    'manage.monitor.bots': '管理和监控您的交易机器人',
    'profit': '利润',
    'roi': '投资回报率',
    'trades': '交易',
    'created': '创建时间',
    'active': '活跃',
    'paused': '暂停',
    'start': '开始',
    'pause': '暂停',
    'error': '错误',
    'total.bots': '总机器人数',
    
    // Bot Templates
    'preconfigured.bot.strategies': '预配置的机器人策略，随时可部署',
    'use.template': '使用模板',
    
    // Manual Trading
    'execute.trades.manually': '使用实时市场数据手动执行交易',
    'trading.chart': '交易图表',
    'tradingview.chart.placeholder': 'TradingView 图表占位符',
    'place.order': '下单',
    'buy': '买入',
    'sell': '卖出',
    'order.type': '订单类型',
    'select.order.type': '选择订单类型',
    'market': '市价',
    'limit': '限价',
    'stop': '止损',
    'price': '价格',
    'amount': '数量',
    'order.book': '订单簿',
    
    // Paper Trading
    'practice.trading.strategies': '使用虚拟资金练习交易策略',
    'virtual.balance': '虚拟余额',
    'paper.pnl': '模拟盈亏',
    'paper.trades': '模拟交易',
    'paper.trading.history': '模拟交易历史',
    'closed': '已关闭',
    'open': '开放',
    'start.new.paper.trading': '开始新的模拟交易会话',
    'reset.virtual.balance': '重置虚拟余额并重新开始',
    
    // Live Charts
    'realtime.trading.charts': '带有技术指标的实时交易图表',
    'advanced.tradingview.chart': '高级 TradingView 图表集成',
    
    // Bot Performance
    'detailed.performance.metrics': '所有交易机器人的详细性能指标',

    // Markets module
    'scan.markets.opportunities': '通过技术分析扫描市场交易机会',
    'scan.results': '扫描结果',
    'strong.buy': '强力买入',
    'hold': '持有',
    
    // Exchange API module
    'connect.manage.exchanges': '连接和管理您的交易所账户',
    'connected.exchanges': '已连接交易所',
    'exchange.name': '交易所名称',
    'api.status': 'API状态',
    'last.sync': '上次同步',
    'actions': '操作',
    'connected': '已连接',
    'disconnected': '已断开',
    'configure': '配置',
    'disconnect': '断开连接',
    'add.new.exchange': '添加新交易所',
    'select.exchange': '选择交易所',
    'api.key': 'API密钥',
    'api.secret': 'API密钥',
    'passphrase': '密码短语',
    'sandbox.mode': '沙盒模式',
    'test.connection': '测试连接',
    'save.configuration': '保存配置',
    
    // Alerts module
    'create.manage.alerts': '创建和管理价格提醒和通知',
    'active.alerts': '活跃提醒',
    'above': '高于',
    'below': '低于',
    'notification.method': '通知方式',
    
    // Strategy module
    'build.test.strategies': '构建和测试您的自定义交易策略',
    'strategy.name': '策略名称',
    'strategy.description': '策略描述',
    'indicators': '指标',
    'conditions': '条件',
    'add.indicator': '添加指标',
    'add.condition': '添加条件',
    'rsi': 'RSI',
    'macd': 'MACD',
    'bollinger.bands': '布林带',
    'moving.average': '移动平均线',
    'greater.than': '大于',
    'less.than': '小于',
    'crosses.above': '上穿',
    'crosses.below': '下穿',
    'save.strategy': '保存策略',
    'test.strategy': '测试策略',
    'deploy.strategy': '部署策略',
    
    // Settings module
    'settings': '设置',
    'manage.account.preferences': '管理账户和应用程序偏好设置',
    'profile.information': '个人资料信息',
    'full.name': '全名',
    'email.address': '邮箱地址',
    'phone.number': '电话号码',
    'update.profile': '更新个人资料',
    'security.settings': '安全设置',
    'change.password': '更改密码',
    'current.password': '当前密码',
    'new.password': '新密码',
    'confirm.password': '确认密码',
    'update.password': '更新密码',
    'two.factor.authentication': '双重身份验证',
    'enable.2fa': '启用2FA',
    'disable.2fa': '禁用2FA',
    'notification.preferences': '通知偏好',
    'trade.notifications': '交易通知',
    'price.alerts.notifications': '价格提醒',
    'system.updates': '系统更新',
    'marketing.emails': '营销邮件',
    
    // Help module
    'get.help.support': '获取使用平台的帮助和支持',
    'frequently.asked.questions': '常见问题',
    'how.to.create.bot': '如何创建交易机器人？',
    'how.to.connect.exchange': '如何连接我的交易所？',
    'how.to.set.alerts': '如何设置价格提醒？',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': '支持时间：24/7',
    'send.message': '发送消息',
    'subject': '主题',
    'message': '消息',
    'send': '发送',
    'user.guides': '用户指南',
    'getting.started.guide': '入门指南',
    'advanced.trading.guide': '高级交易指南',
    'api.documentation': 'API文档',
    'video.tutorials': '视频教程',
    'view.guide': '查看指南',
    'watch.tutorial': '观看教程',
  }
};
