
import React, { createContext, useContext, useState, useEffect } from 'react';

type Language = 'en' | 'ar' | 'es' | 'fr' | 'hi' | 'de' | 'pt' | 'zh';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  en: {
    // Dashboard
    'dashboard': 'Dashboard',
    'welcome.back': 'Welcome back! Here\'s what\'s happening with your trading.',
    
    // Navigation
    'my.bots': 'My Bots',
    'create.new.bot': 'Create New Bot',
    'bot.templates': 'Bot Templates',
    'strategy.builder': 'Strategy Builder',
    'saved.strategies': 'Saved Strategies',
    'strategy.marketplace': 'Strategy Marketplace',
    'build.strategy': 'Build Strategy',
    'market.overview': 'Market Overview',
    'market.scanner': 'Market Scanner',
    'live.charts': 'Live Charts',
    'watchlist': 'Watchlist',
    'price.alerts': 'Price Alerts',
    'manual.trading': 'Manual Trading',
    'signal.trading': 'Signal Trading',
    'paper.trading': 'Paper Trading',
    'exchanges': 'Exchanges',
    'exchanges.api': 'Exchanges & API',
    'sync.balances': 'Sync Balances',
    'alerts': 'Alerts',
    'alert.logs': 'Alert Logs',
    'create.alert': 'Create Alert',
    'notification.settings': 'Notification Settings',
    'backtesting': 'Backtesting',
    'performance': 'Performance',
    'api.management': 'API Management',
    'session.logs': 'Session Logs',
    'profile.settings': 'Profile Settings',
    'theme.settings': 'Theme Settings',
    'two.factor.auth': 'Two-Factor Auth',
    'help': 'Help',
    'documentation': 'Documentation',
    'community': 'Community',
    'contact.support': 'Contact Support',
    'bug.reports': 'Bug Reports',
    
    // Bot related
    'bot.name': 'Bot Name',
    'trading.pair': 'Trading Pair',
    'strategy.type': 'Strategy Type',
    'investment.amount': 'Investment Amount',
    'enter.bot.name': 'Enter bot name',
    'select.trading.pair': 'Select trading pair',
    'select.strategy': 'Select strategy',
    'enter.amount.usdt': 'Enter amount in USDT',
    'create.bot': 'Create Bot',
    'manage.monitor.bots': 'Manage and monitor your trading bots',
    'active': 'Active',
    'paused': 'Paused',
    'error': 'Error',
    'profit': 'Profit',
    'roi': 'ROI',
    'trades': 'Trades',
    'created': 'Created',
    'pause': 'Pause',
    'start': 'Start',
    'total.bots': 'Total Bots',
    'bot.performance': 'Bot Performance',
    'detailed.performance.metrics': 'Detailed performance metrics for your bots',
    
    // Templates
    'strategy.templates': 'Strategy Templates',
    'preconfigured.bot.strategies': 'Pre-configured bot strategies ready to use',
    'use.template': 'Use Template',
    
    // Trading
    'buy': 'Buy',
    'sell': 'Sell',
    'hold': 'Hold',
    'strong.buy': 'Strong Buy',
    'amount': 'Amount',
    'price': 'Price',
    'total': 'Total',
    'market': 'Market',
    'limit': 'Limit',
    'order.type': 'Order Type',
    'place.order': 'Place Order',
    'order.book': 'Order Book',
    'recent.trades': 'Recent Trades',
    'open.positions': 'Open Positions',
    'order.history': 'Order History',
    'paper.mode': 'Paper Mode',
    'live.mode': 'Live Mode',
    'virtual.balance': 'Virtual Balance',
    'simulate.trading': 'Simulate trading without real money',
    'real.trading': 'Real trading with actual funds',
    
    // Markets
    'scan.markets.opportunities': 'Scan markets for trading opportunities',
    'scan.results': 'Scan Results',
    'vol': 'Vol',
    'top.gainers': 'Top Gainers',
    'top.losers': 'Top Losers',
    'most.active': 'Most Active',
    'trending.coins': 'Trending Coins',
    'market.cap': 'Market Cap',
    'volume.24h': 'Volume 24h',
    'change.24h': 'Change 24h',
    
    // Exchange & API
    'connect.manage.exchanges': 'Connect and manage your exchange accounts',
    'add.new.exchange': 'Add New Exchange',
    'connected.exchanges': 'Connected Exchanges',
    'exchange.name': 'Exchange Name',
    'api.status': 'API Status',
    'last.sync': 'Last Sync',
    'actions': 'Actions',
    'connected': 'Connected',
    'disconnected': 'Disconnected',
    'configure': 'Configure',
    'disconnect': 'Disconnect',
    'select.exchange': 'Select Exchange',
    'api.key': 'API Key',
    'api.secret': 'API Secret',
    'passphrase': 'Passphrase',
    'sandbox.mode': 'Sandbox Mode',
    'test.connection': 'Test Connection',
    'save.configuration': 'Save Configuration',
    
    // Alerts
    'create.new.alert': 'Create New Alert',
    'manage.price.alerts': 'Manage your price alerts and notifications',
    'asset': 'Asset',
    'condition': 'Condition',
    'target.price': 'Target Price',
    'notification.method': 'Notification Method',
    'alert.name': 'Alert Name',
    'select.asset': 'Select Asset',
    'select.condition': 'Select Condition',
    'above': 'Above',
    'below': 'Below',
    'email': 'Email',
    'push': 'Push',
    'sms': 'SMS',
    'create.alert': 'Create Alert',
    'active.alerts': 'Active Alerts',
    'triggered.alerts': 'Triggered Alerts',
    'current.price': 'Current Price',
    'status': 'Status',
    'triggered': 'Triggered',
    
    // Strategy Builder
    'create.custom.strategies': 'Create and customize your trading strategies',
    'strategy.name': 'Strategy Name',
    'enter.strategy.name': 'Enter strategy name',
    'timeframe': 'Timeframe',
    'select.timeframe': 'Select timeframe',
    'entry.conditions': 'Entry Conditions',
    'exit.conditions': 'Exit Conditions',
    'risk.management': 'Risk Management',
    'add.condition': 'Add Condition',
    'stop.loss': 'Stop Loss (%)',
    'take.profit': 'Take Profit (%)',
    'save.strategy': 'Save Strategy',
    'test.strategy': 'Test Strategy',
    'my.strategies': 'My Strategies',
    'public.strategies': 'Public Strategies',
    'strategy.performance': 'Strategy Performance',
    'backtest.results': 'Backtest Results',
    
    // Settings
    'account.settings': 'Account Settings',
    'security.settings': 'Security Settings',
    'appearance': 'Appearance',
    'language': 'Language',
    'select.language': 'Select Language',
    'dark.mode': 'Dark Mode',
    'light.mode': 'Light Mode',
    'system': 'System',
    'notifications': 'Notifications',
    'enable.notifications': 'Enable Notifications',
    'save.changes': 'Save Changes',
    'change.password': 'Change Password',
    'current.password': 'Current Password',
    'new.password': 'New Password',
    'confirm.password': 'Confirm Password',
    'update.password': 'Update Password',
    
    // Help & Support
    'get.help.support': 'Get help and support for using the platform',
    'frequently.asked.questions': 'Frequently Asked Questions',
    'contact.support': 'Contact Support',
    'user.guides': 'User Guides',
    'how.to.create.bot': 'How do I create a trading bot?',
    'how.to.connect.exchange': 'How do I connect my exchange?',
    'how.to.set.alerts': 'How do I set up price alerts?',
    'getting.started.guide': 'Getting Started Guide',
    'advanced.trading.guide': 'Advanced Trading Guide',
    'api.documentation': 'API Documentation',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'Support Hours: 24/7',
    'subject': 'Subject',
    'message': 'Message',
    'send.message': 'Send Message',
    'watch.tutorial': 'Watch Tutorial',
    'view.guide': 'View Guide',
  },
  ar: {
    // Dashboard
    'dashboard': 'لوحة التحكم',
    'welcome.back': 'مرحباً بعودتك! إليك ما يحدث مع تداولك.',
    
    // Navigation
    'my.bots': 'روبوتاتي',
    'create.new.bot': 'إنشاء روبوت جديد',
    'bot.templates': 'قوالب الروبوت',
    'strategy.builder': 'منشئ الاستراتيجية',
    'saved.strategies': 'الاستراتيجيات المحفوظة',
    'strategy.marketplace': 'سوق الاستراتيجيات',
    'build.strategy': 'بناء الاستراتيجية',
    'market.overview': 'نظرة عامة على السوق',
    'market.scanner': 'ماسح السوق',
    'live.charts': 'الرسوم البيانية المباشرة',
    'watchlist': 'قائمة المراقبة',
    'price.alerts': 'تنبيهات الأسعار',
    'manual.trading': 'التداول اليدوي',
    'signal.trading': 'تداول الإشارات',
    'paper.trading': 'التداول الورقي',
    'exchanges': 'البورصات',
    'exchanges.api': 'البورصات وواجهة برمجة التطبيقات',
    'sync.balances': 'مزامنة الأرصدة',
    'alerts': 'التنبيهات',
    'alert.logs': 'سجلات التنبيه',
    'create.alert': 'إنشاء تنبيه',
    'notification.settings': 'إعدادات الإشعارات',
    'backtesting': 'الاختبار الخلفي',
    'performance': 'الأداء',
    'api.management': 'إدارة واجهة برمجة التطبيقات',
    'session.logs': 'سجلات الجلسة',
    'profile.settings': 'إعدادات الملف الشخصي',
    'theme.settings': 'إعدادات المظهر',
    'two.factor.auth': 'المصادقة الثنائية',
    'help': 'المساعدة',
    'documentation': 'التوثيق',
    'community': 'المجتمع',
    'contact.support': 'اتصل بالدعم',
    'bug.reports': 'تقارير الأخطاء',
    
    // Bot related
    'bot.name': 'اسم الروبوت',
    'trading.pair': 'زوج التداول',
    'strategy.type': 'نوع الاستراتيجية',
    'investment.amount': 'مبلغ الاستثمار',
    'enter.bot.name': 'أدخل اسم الروبوت',
    'select.trading.pair': 'اختر زوج التداول',
    'select.strategy': 'اختر الاستراتيجية',
    'enter.amount.usdt': 'أدخل المبلغ بالدولار الرقمي',
    'create.bot': 'إنشاء روبوت',
    'manage.monitor.bots': 'إدارة ومراقبة روبوتات التداول الخاصة بك',
    'active': 'نشط',
    'paused': 'متوقف مؤقتاً',
    'error': 'خطأ',
    'profit': 'الربح',
    'roi': 'العائد على الاستثمار',
    'trades': 'الصفقات',
    'created': 'تم الإنشاء',
    'pause': 'إيقاف مؤقت',
    'start': 'بدء',
    'total.bots': 'إجمالي الروبوتات',
    'bot.performance': 'أداء الروبوت',
    'detailed.performance.metrics': 'مقاييس الأداء التفصيلية لروبوتاتك',
    
    // Templates
    'strategy.templates': 'قوالب الاستراتيجية',
    'preconfigured.bot.strategies': 'استراتيجيات روبوت مُعدة مسبقاً جاهزة للاستخدام',
    'use.template': 'استخدام القالب',
    
    // Trading
    'buy': 'شراء',
    'sell': 'بيع',
    'hold': 'احتفاظ',
    'strong.buy': 'شراء قوي',
    'amount': 'المبلغ',
    'price': 'السعر',
    'total': 'الإجمالي',
    'market': 'السوق',
    'limit': 'محدود',
    'order.type': 'نوع الأمر',
    'place.order': 'تنفيذ الأمر',
    'order.book': 'دفتر الأوامر',
    'recent.trades': 'الصفقات الأخيرة',
    'open.positions': 'المراكز المفتوحة',
    'order.history': 'تاريخ الأوامر',
    'paper.mode': 'الوضع الورقي',
    'live.mode': 'الوضع المباشر',
    'virtual.balance': 'الرصيد الافتراضي',
    'simulate.trading': 'محاكاة التداول بدون أموال حقيقية',
    'real.trading': 'التداول الحقيقي بأموال فعلية',
    
    // Markets
    'scan.markets.opportunities': 'فحص الأسواق للعثور على فرص التداول',
    'scan.results': 'نتائج الفحص',
    'vol': 'الحجم',
    'top.gainers': 'أكبر الرابحين',
    'top.losers': 'أكبر الخاسرين',
    'most.active': 'الأكثر نشاطاً',
    'trending.coins': 'العملات الرائجة',
    'market.cap': 'القيمة السوقية',
    'volume.24h': 'حجم 24 ساعة',
    'change.24h': 'تغيير 24 ساعة',
    
    // Exchange & API
    'connect.manage.exchanges': 'ربط وإدارة حسابات البورصة الخاصة بك',
    'add.new.exchange': 'إضافة بورصة جديدة',
    'connected.exchanges': 'البورصات المتصلة',
    'exchange.name': 'اسم البورصة',
    'api.status': 'حالة واجهة برمجة التطبيقات',
    'last.sync': 'آخر مزامنة',
    'actions': 'الإجراءات',
    'connected': 'متصل',
    'disconnected': 'منقطع',
    'configure': 'تكوين',
    'disconnect': 'قطع الاتصال',
    'select.exchange': 'اختر البورصة',
    'api.key': 'مفتاح واجهة برمجة التطبيقات',
    'api.secret': 'سر واجهة برمجة التطبيقات',
    'passphrase': 'كلمة المرور',
    'sandbox.mode': 'وضع الاختبار',
    'test.connection': 'اختبار الاتصال',
    'save.configuration': 'حفظ التكوين',
    
    // Alerts
    'create.new.alert': 'إنشاء تنبيه جديد',
    'manage.price.alerts': 'إدارة تنبيهات الأسعار والإشعارات',
    'asset': 'الأصل',
    'condition': 'الشرط',
    'target.price': 'السعر المستهدف',
    'notification.method': 'طريقة الإشعار',
    'alert.name': 'اسم التنبيه',
    'select.asset': 'اختر الأصل',
    'select.condition': 'اختر الشرط',
    'above': 'أعلى من',
    'below': 'أقل من',
    'email': 'البريد الإلكتروني',
    'push': 'إشعار فوري',
    'sms': 'رسالة نصية',
    'create.alert': 'إنشاء تنبيه',
    'active.alerts': 'التنبيهات النشطة',
    'triggered.alerts': 'التنبيهات المفعلة',
    'current.price': 'السعر الحالي',
    'status': 'الحالة',
    'triggered': 'مفعل',
    
    // Strategy Builder
    'create.custom.strategies': 'إنشاء وتخصيص استراتيجيات التداول الخاصة بك',
    'strategy.name': 'اسم الاستراتيجية',
    'enter.strategy.name': 'أدخل اسم الاستراتيجية',
    'timeframe': 'الإطار الزمني',
    'select.timeframe': 'اختر الإطار الزمني',
    'entry.conditions': 'شروط الدخول',
    'exit.conditions': 'شروط الخروج',
    'risk.management': 'إدارة المخاطر',
    'add.condition': 'إضافة شرط',
    'stop.loss': 'وقف الخسائر (%)',
    'take.profit': 'جني الأرباح (%)',
    'save.strategy': 'حفظ الاستراتيجية',
    'test.strategy': 'اختبار الاستراتيجية',
    'my.strategies': 'استراتيجياتي',
    'public.strategies': 'الاستراتيجيات العامة',
    'strategy.performance': 'أداء الاستراتيجية',
    'backtest.results': 'نتائج الاختبار الخلفي',
    
    // Settings
    'account.settings': 'إعدادات الحساب',
    'security.settings': 'إعدادات الأمان',
    'appearance': 'المظهر',
    'language': 'اللغة',
    'select.language': 'اختر اللغة',
    'dark.mode': 'الوضع المظلم',
    'light.mode': 'الوضع الفاتح',
    'system': 'النظام',
    'notifications': 'الإشعارات',
    'enable.notifications': 'تفعيل الإشعارات',
    'save.changes': 'حفظ التغييرات',
    'change.password': 'تغيير كلمة المرور',
    'current.password': 'كلمة المرور الحالية',
    'new.password': 'كلمة المرور الجديدة',
    'confirm.password': 'تأكيد كلمة المرور',
    'update.password': 'تحديث كلمة المرور',
    
    // Help & Support
    'get.help.support': 'احصل على المساعدة والدعم لاستخدام المنصة',
    'frequently.asked.questions': 'الأسئلة الشائعة',
    'contact.support': 'اتصل بالدعم',
    'user.guides': 'أدلة المستخدم',
    'how.to.create.bot': 'كيف أنشئ روبوت تداول؟',
    'how.to.connect.exchange': 'كيف أربط البورصة الخاصة بي؟',
    'how.to.set.alerts': 'كيف أضع تنبيهات الأسعار؟',
    'getting.started.guide': 'دليل البدء',
    'advanced.trading.guide': 'دليل التداول المتقدم',
    'api.documentation': 'توثيق واجهة برمجة التطبيقات',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'ساعات الدعم: 24/7',
    'subject': 'الموضوع',
    'message': 'الرسالة',
    'send.message': 'إرسال الرسالة',
    'watch.tutorial': 'مشاهدة البرنامج التعليمي',
    'view.guide': 'عرض الدليل',
  },
  es: {
    // Dashboard
    'dashboard': 'Panel de Control',
    'welcome.back': '¡Bienvenido de vuelta! Esto es lo que está pasando con tu trading.',
    
    // Navigation
    'my.bots': 'Mis Bots',
    'create.new.bot': 'Crear Nuevo Bot',
    'bot.templates': 'Plantillas de Bot',
    'strategy.builder': 'Constructor de Estrategias',
    'saved.strategies': 'Estrategias Guardadas',
    'strategy.marketplace': 'Mercado de Estrategias',
    'build.strategy': 'Construir Estrategia',
    'market.overview': 'Resumen del Mercado',
    'market.scanner': 'Escáner de Mercado',
    'live.charts': 'Gráficos en Vivo',
    'watchlist': 'Lista de Seguimiento',
    'price.alerts': 'Alertas de Precio',
    'manual.trading': 'Trading Manual',
    'signal.trading': 'Trading de Señales',
    'paper.trading': 'Trading Virtual',
    'exchanges': 'Intercambios',
    'exchanges.api': 'Intercambios y API',
    'sync.balances': 'Sincronizar Balances',
    'alerts': 'Alertas',
    'alert.logs': 'Registros de Alertas',
    'create.alert': 'Crear Alerta',
    'notification.settings': 'Configuración de Notificaciones',
    'backtesting': 'Backtesting',
    'performance': 'Rendimiento',
    'api.management': 'Gestión de API',
    'session.logs': 'Registros de Sesión',
    'profile.settings': 'Configuración de Perfil',
    'theme.settings': 'Configuración de Tema',
    'two.factor.auth': 'Autenticación de Dos Factores',
    'help': 'Ayuda',
    'documentation': 'Documentación',
    'community': 'Comunidad',
    'contact.support': 'Contactar Soporte',
    'bug.reports': 'Reportes de Errores',
    
    // Bot related
    'bot.name': 'Nombre del Bot',
    'trading.pair': 'Par de Trading',
    'strategy.type': 'Tipo de Estrategia',
    'investment.amount': 'Cantidad de Inversión',
    'enter.bot.name': 'Ingresa el nombre del bot',
    'select.trading.pair': 'Selecciona el par de trading',
    'select.strategy': 'Selecciona la estrategia',
    'enter.amount.usdt': 'Ingresa la cantidad en USDT',
    'create.bot': 'Crear Bot',
    'manage.monitor.bots': 'Gestiona y monitorea tus bots de trading',
    'active': 'Activo',
    'paused': 'Pausado',
    'error': 'Error',
    'profit': 'Ganancia',
    'roi': 'ROI',
    'trades': 'Operaciones',
    'created': 'Creado',
    'pause': 'Pausar',
    'start': 'Iniciar',
    'total.bots': 'Total de Bots',
    'bot.performance': 'Rendimiento del Bot',
    'detailed.performance.metrics': 'Métricas detalladas de rendimiento para tus bots',
    
    // Templates
    'strategy.templates': 'Plantillas de Estrategia',
    'preconfigured.bot.strategies': 'Estrategias de bot preconfiguradas listas para usar',
    'use.template': 'Usar Plantilla',
    
    // Trading
    'buy': 'Comprar',
    'sell': 'Vender',
    'hold': 'Mantener',
    'strong.buy': 'Compra Fuerte',
    'amount': 'Cantidad',
    'price': 'Precio',
    'total': 'Total',
    'market': 'Mercado',
    'limit': 'Límite',
    'order.type': 'Tipo de Orden',
    'place.order': 'Colocar Orden',
    'order.book': 'Libro de Órdenes',
    'recent.trades': 'Operaciones Recientes',
    'open.positions': 'Posiciones Abiertas',
    'order.history': 'Historial de Órdenes',
    'paper.mode': 'Modo Virtual',
    'live.mode': 'Modo Real',
    'virtual.balance': 'Balance Virtual',
    'simulate.trading': 'Simular trading sin dinero real',
    'real.trading': 'Trading real con fondos reales',
    
    // Markets
    'scan.markets.opportunities': 'Escanear mercados en busca de oportunidades de trading',
    'scan.results': 'Resultados del Escaneo',
    'vol': 'Vol',
    'top.gainers': 'Mayores Ganadores',
    'top.losers': 'Mayores Perdedores',
    'most.active': 'Más Activos',
    'trending.coins': 'Monedas Trending',
    'market.cap': 'Cap. de Mercado',
    'volume.24h': 'Volumen 24h',
    'change.24h': 'Cambio 24h',
    
    // Exchange & API
    'connect.manage.exchanges': 'Conecta y gestiona tus cuentas de intercambio',
    'add.new.exchange': 'Agregar Nuevo Intercambio',
    'connected.exchanges': 'Intercambios Conectados',
    'exchange.name': 'Nombre del Intercambio',
    'api.status': 'Estado de API',
    'last.sync': 'Última Sincronización',
    'actions': 'Acciones',
    'connected': 'Conectado',
    'disconnected': 'Desconectado',
    'configure': 'Configurar',
    'disconnect': 'Desconectar',
    'select.exchange': 'Seleccionar Intercambio',
    'api.key': 'Clave API',
    'api.secret': 'Secreto API',
    'passphrase': 'Frase de Paso',
    'sandbox.mode': 'Modo Sandbox',
    'test.connection': 'Probar Conexión',
    'save.configuration': 'Guardar Configuración',
    
    // Alerts
    'create.new.alert': 'Crear Nueva Alerta',
    'manage.price.alerts': 'Gestiona tus alertas de precio y notificaciones',
    'asset': 'Activo',
    'condition': 'Condición',
    'target.price': 'Precio Objetivo',
    'notification.method': 'Método de Notificación',
    'alert.name': 'Nombre de la Alerta',
    'select.asset': 'Seleccionar Activo',
    'select.condition': 'Seleccionar Condición',
    'above': 'Por Encima',
    'below': 'Por Debajo',
    'email': 'Correo Electrónico',
    'push': 'Push',
    'sms': 'SMS',
    'create.alert': 'Crear Alerta',
    'active.alerts': 'Alertas Activas',
    'triggered.alerts': 'Alertas Activadas',
    'current.price': 'Precio Actual',
    'status': 'Estado',
    'triggered': 'Activado',
    
    // Strategy Builder
    'create.custom.strategies': 'Crea y personaliza tus estrategias de trading',
    'strategy.name': 'Nombre de la Estrategia',
    'enter.strategy.name': 'Ingresa el nombre de la estrategia',
    'timeframe': 'Marco Temporal',
    'select.timeframe': 'Seleccionar marco temporal',
    'entry.conditions': 'Condiciones de Entrada',
    'exit.conditions': 'Condiciones de Salida',
    'risk.management': 'Gestión de Riesgos',
    'add.condition': 'Agregar Condición',
    'stop.loss': 'Stop Loss (%)',
    'take.profit': 'Take Profit (%)',
    'save.strategy': 'Guardar Estrategia',
    'test.strategy': 'Probar Estrategia',
    'my.strategies': 'Mis Estrategias',
    'public.strategies': 'Estrategias Públicas',
    'strategy.performance': 'Rendimiento de Estrategia',
    'backtest.results': 'Resultados de Backtest',
    
    // Settings
    'account.settings': 'Configuración de Cuenta',
    'security.settings': 'Configuración de Seguridad',
    'appearance': 'Apariencia',
    'language': 'Idioma',
    'select.language': 'Seleccionar Idioma',
    'dark.mode': 'Modo Oscuro',
    'light.mode': 'Modo Claro',
    'system': 'Sistema',
    'notifications': 'Notificaciones',
    'enable.notifications': 'Habilitar Notificaciones',
    'save.changes': 'Guardar Cambios',
    'change.password': 'Cambiar Contraseña',
    'current.password': 'Contraseña Actual',
    'new.password': 'Nueva Contraseña',
    'confirm.password': 'Confirmar Contraseña',
    'update.password': 'Actualizar Contraseña',
    
    // Help & Support
    'get.help.support': 'Obtén ayuda y soporte para usar la plataforma',
    'frequently.asked.questions': 'Preguntas Frecuentes',
    'contact.support': 'Contactar Soporte',
    'user.guides': 'Guías de Usuario',
    'how.to.create.bot': '¿Cómo creo un bot de trading?',
    'how.to.connect.exchange': '¿Cómo conecto mi intercambio?',
    'how.to.set.alerts': '¿Cómo configuro alertas de precio?',
    'getting.started.guide': 'Guía de Inicio',
    'advanced.trading.guide': 'Guía de Trading Avanzado',
    'api.documentation': 'Documentación de API',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'Horarios de Soporte: 24/7',
    'subject': 'Asunto',
    'message': 'Mensaje',
    'send.message': 'Enviar Mensaje',
    'watch.tutorial': 'Ver Tutorial',
    'view.guide': 'Ver Guía',
  },
  fr: {
    // Dashboard
    'dashboard': 'Tableau de Bord',
    'welcome.back': 'Bon retour! Voici ce qui se passe avec votre trading.',
    
    // Navigation
    'my.bots': 'Mes Bots',
    'create.new.bot': 'Créer un Nouveau Bot',
    'bot.templates': 'Modèles de Bot',
    'strategy.builder': 'Constructeur de Stratégie',
    'saved.strategies': 'Stratégies Sauvegardées',
    'strategy.marketplace': 'Marché des Stratégies',
    'build.strategy': 'Construire une Stratégie',
    'market.overview': 'Aperçu du Marché',
    'market.scanner': 'Scanner de Marché',
    'live.charts': 'Graphiques en Direct',
    'watchlist': 'Liste de Surveillance',
    'price.alerts': 'Alertes de Prix',
    'manual.trading': 'Trading Manuel',
    'signal.trading': 'Trading de Signaux',
    'paper.trading': 'Trading Virtuel',
    'exchanges': 'Échanges',
    'exchanges.api': 'Échanges et API',
    'sync.balances': 'Synchroniser les Soldes',
    'alerts': 'Alertes',
    'alert.logs': 'Journaux d\'Alertes',
    'create.alert': 'Créer une Alerte',
    'notification.settings': 'Paramètres de Notification',
    'backtesting': 'Backtesting',
    'performance': 'Performance',
    'api.management': 'Gestion API',
    'session.logs': 'Journaux de Session',
    'profile.settings': 'Paramètres de Profil',
    'theme.settings': 'Paramètres de Thème',
    'two.factor.auth': 'Authentification à Deux Facteurs',
    'help': 'Aide',
    'documentation': 'Documentation',
    'community': 'Communauté',
    'contact.support': 'Contacter le Support',
    'bug.reports': 'Rapports de Bugs',
    
    // Bot related
    'bot.name': 'Nom du Bot',
    'trading.pair': 'Paire de Trading',
    'strategy.type': 'Type de Stratégie',
    'investment.amount': 'Montant d\'Investissement',
    'enter.bot.name': 'Entrez le nom du bot',
    'select.trading.pair': 'Sélectionnez la paire de trading',
    'select.strategy': 'Sélectionnez la stratégie',
    'enter.amount.usdt': 'Entrez le montant en USDT',
    'create.bot': 'Créer un Bot',
    'manage.monitor.bots': 'Gérez et surveillez vos bots de trading',
    'active': 'Actif',
    'paused': 'En Pause',
    'error': 'Erreur',
    'profit': 'Profit',
    'roi': 'ROI',
    'trades': 'Transactions',
    'created': 'Créé',
    'pause': 'Pause',
    'start': 'Démarrer',
    'total.bots': 'Total des Bots',
    'bot.performance': 'Performance du Bot',
    'detailed.performance.metrics': 'Métriques de performance détaillées pour vos bots',
    
    // Templates
    'strategy.templates': 'Modèles de Stratégie',
    'preconfigured.bot.strategies': 'Stratégies de bot préconfigurées prêtes à utiliser',
    'use.template': 'Utiliser le Modèle',
    
    // Trading
    'buy': 'Acheter',
    'sell': 'Vendre',
    'hold': 'Conserver',
    'strong.buy': 'Achat Fort',
    'amount': 'Montant',
    'price': 'Prix',
    'total': 'Total',
    'market': 'Marché',
    'limit': 'Limite',
    'order.type': 'Type d\'Ordre',
    'place.order': 'Passer l\'Ordre',
    'order.book': 'Carnet d\'Ordres',
    'recent.trades': 'Transactions Récentes',
    'open.positions': 'Positions Ouvertes',
    'order.history': 'Historique des Ordres',
    'paper.mode': 'Mode Virtuel',
    'live.mode': 'Mode Réel',
    'virtual.balance': 'Solde Virtuel',
    'simulate.trading': 'Simuler le trading sans argent réel',
    'real.trading': 'Trading réel avec des fonds réels',
    
    // Markets
    'scan.markets.opportunities': 'Scanner les marchés pour des opportunités de trading',
    'scan.results': 'Résultats du Scan',
    'vol': 'Vol',
    'top.gainers': 'Plus Gros Gagnants',
    'top.losers': 'Plus Gros Perdants',
    'most.active': 'Plus Actifs',
    'trending.coins': 'Pièces Tendance',
    'market.cap': 'Cap. Boursière',
    'volume.24h': 'Volume 24h',
    'change.24h': 'Changement 24h',
    
    // Exchange & API
    'connect.manage.exchanges': 'Connectez et gérez vos comptes d\'échange',
    'add.new.exchange': 'Ajouter un Nouvel Échange',
    'connected.exchanges': 'Échanges Connectés',
    'exchange.name': 'Nom de l\'Échange',
    'api.status': 'Statut API',
    'last.sync': 'Dernière Synchronisation',
    'actions': 'Actions',
    'connected': 'Connecté',
    'disconnected': 'Déconnecté',
    'configure': 'Configurer',
    'disconnect': 'Déconnecter',
    'select.exchange': 'Sélectionner l\'Échange',
    'api.key': 'Clé API',
    'api.secret': 'Secret API',
    'passphrase': 'Phrase de Passe',
    'sandbox.mode': 'Mode Sandbox',
    'test.connection': 'Tester la Connexion',
    'save.configuration': 'Sauvegarder la Configuration',
    
    // Alerts
    'create.new.alert': 'Créer une Nouvelle Alerte',
    'manage.price.alerts': 'Gérez vos alertes de prix et notifications',
    'asset': 'Actif',
    'condition': 'Condition',
    'target.price': 'Prix Cible',
    'notification.method': 'Méthode de Notification',
    'alert.name': 'Nom de l\'Alerte',
    'select.asset': 'Sélectionner l\'Actif',
    'select.condition': 'Sélectionner la Condition',
    'above': 'Au-dessus',
    'below': 'En-dessous',
    'email': 'Email',
    'push': 'Push',
    'sms': 'SMS',
    'create.alert': 'Créer une Alerte',
    'active.alerts': 'Alertes Actives',
    'triggered.alerts': 'Alertes Déclenchées',
    'current.price': 'Prix Actuel',
    'status': 'Statut',
    'triggered': 'Déclenché',
    
    // Strategy Builder
    'create.custom.strategies': 'Créez et personnalisez vos stratégies de trading',
    'strategy.name': 'Nom de la Stratégie',
    'enter.strategy.name': 'Entrez le nom de la stratégie',
    'timeframe': 'Période',
    'select.timeframe': 'Sélectionner la période',
    'entry.conditions': 'Conditions d\'Entrée',
    'exit.conditions': 'Conditions de Sortie',
    'risk.management': 'Gestion des Risques',
    'add.condition': 'Ajouter une Condition',
    'stop.loss': 'Stop Loss (%)',
    'take.profit': 'Take Profit (%)',
    'save.strategy': 'Sauvegarder la Stratégie',
    'test.strategy': 'Tester la Stratégie',
    'my.strategies': 'Mes Stratégies',
    'public.strategies': 'Stratégies Publiques',
    'strategy.performance': 'Performance de la Stratégie',
    'backtest.results': 'Résultats du Backtest',
    
    // Settings
    'account.settings': 'Paramètres du Compte',
    'security.settings': 'Paramètres de Sécurité',
    'appearance': 'Apparence',
    'language': 'Langue',
    'select.language': 'Sélectionner la Langue',
    'dark.mode': 'Mode Sombre',
    'light.mode': 'Mode Clair',
    'system': 'Système',
    'notifications': 'Notifications',
    'enable.notifications': 'Activer les Notifications',
    'save.changes': 'Sauvegarder les Changements',
    'change.password': 'Changer le Mot de Passe',
    'current.password': 'Mot de Passe Actuel',
    'new.password': 'Nouveau Mot de Passe',
    'confirm.password': 'Confirmer le Mot de Passe',
    'update.password': 'Mettre à Jour le Mot de Passe',
    
    // Help & Support
    'get.help.support': 'Obtenez de l\'aide et du support pour utiliser la plateforme',
    'frequently.asked.questions': 'Questions Fréquemment Posées',
    'contact.support': 'Contacter le Support',
    'user.guides': 'Guides Utilisateur',
    'how.to.create.bot': 'Comment créer un bot de trading?',
    'how.to.connect.exchange': 'Comment connecter mon échange?',
    'how.to.set.alerts': 'Comment configurer les alertes de prix?',
    'getting.started.guide': 'Guide de Démarrage',
    'advanced.trading.guide': 'Guide de Trading Avancé',
    'api.documentation': 'Documentation API',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'Heures de Support: 24/7',
    'subject': 'Sujet',
    'message': 'Message',
    'send.message': 'Envoyer le Message',
    'watch.tutorial': 'Regarder le Tutoriel',
    'view.guide': 'Voir le Guide',
  },
  hi: {
    // Dashboard
    'dashboard': 'डैशबोर्ड',
    'welcome.back': 'वापसी पर स्वागत है! यहाँ आपकी ट्रेडिंग के साथ क्या हो रहा है।',
    
    // Navigation
    'my.bots': 'मेरे बॉट्स',
    'create.new.bot': 'नया बॉट बनाएं',
    'bot.templates': 'बॉट टेम्प्लेट्स',
    'strategy.builder': 'रणनीति निर्माता',
    'saved.strategies': 'सेव की गई रणनीतियां',
    'strategy.marketplace': 'रणनीति मार्केटप्लेस',
    'build.strategy': 'रणनीति बनाएं',
    'market.overview': 'बाजार अवलोकन',
    'market.scanner': 'मार्केट स्कैनर',
    'live.charts': 'लाइव चार्ट्स',
    'watchlist': 'वॉचलिस्ट',
    'price.alerts': 'मूल्य अलर्ट',
    'manual.trading': 'मैन्युअल ट्रेडिंग',
    'signal.trading': 'सिग्नल ट्रेडिंग',
    'paper.trading': 'पेपर ट्रेडिंग',
    'exchanges': 'एक्सचेंजेस',
    'exchanges.api': 'एक्सचेंजेस और एपीआई',
    'sync.balances': 'बैलेंस सिंक करें',
    'alerts': 'अलर्ट्स',
    'alert.logs': 'अलर्ट लॉग्स',
    'create.alert': 'अलर्ट बनाएं',
    'notification.settings': 'नोटिफिकेशन सेटिंग्स',
    'backtesting': 'बैकटेस्टिंग',
    'performance': 'प्रदर्शन',
    'api.management': 'एपीआई प्रबंधन',
    'session.logs': 'सेशन लॉग्स',
    'profile.settings': 'प्रोफाइल सेटिंग्स',
    'theme.settings': 'थीम सेटिंग्स',
    'two.factor.auth': 'दो-कारक प्रमाणीकरण',
    'help': 'सहायता',
    'documentation': 'दस्तावेज़ीकरण',
    'community': 'समुदाय',
    'contact.support': 'सहायता से संपर्क करें',
    'bug.reports': 'बग रिपोर्ट्स',
    
    // Bot related
    'bot.name': 'बॉट का नाम',
    'trading.pair': 'ट्रेडिंग जोड़ी',
    'strategy.type': 'रणनीति का प्रकार',
    'investment.amount': 'निवेश राशि',
    'enter.bot.name': 'बॉट का नाम दर्ज करें',
    'select.trading.pair': 'ट्रेडिंग जोड़ी चुनें',
    'select.strategy': 'रणनीति चुनें',
    'enter.amount.usdt': 'USDT में राशि दर्ज करें',
    'create.bot': 'बॉट बनाएं',
    'manage.monitor.bots': 'अपने ट्रेडिंग बॉट्स का प्रबंधन और निगरानी करें',
    'active': 'सक्रिय',
    'paused': 'रोका गया',
    'error': 'त्रुटि',
    'profit': 'लाभ',
    'roi': 'ROI',
    'trades': 'ट्रेड्स',
    'created': 'बनाया गया',
    'pause': 'रोकें',
    'start': 'शुरू करें',
    'total.bots': 'कुल बॉट्स',
    'bot.performance': 'बॉट प्रदर्शन',
    'detailed.performance.metrics': 'आपके बॉट्स के लिए विस्तृत प्रदर्शन मेट्रिक्स',
    
    // Templates
    'strategy.templates': 'रणनीति टेम्प्लेट्स',
    'preconfigured.bot.strategies': 'पूर्व-कॉन्फ़िगर्ड बॉट रणनीतियां उपयोग के लिए तैयार',
    'use.template': 'टेम्प्लेट का उपयोग करें',
    
    // Trading
    'buy': 'खरीदें',
    'sell': 'बेचें',
    'hold': 'होल्ड करें',
    'strong.buy': 'मजबूत खरीद',
    'amount': 'राशि',
    'price': 'मूल्य',
    'total': 'कुल',
    'market': 'मार्केट',
    'limit': 'लिमिट',
    'order.type': 'ऑर्डर प्रकार',
    'place.order': 'ऑर्डर दें',
    'order.book': 'ऑर्डर बुक',
    'recent.trades': 'हाल की ट्रेड्स',
    'open.positions': 'खुली पोजीशन',
    'order.history': 'ऑर्डर हिस्ट्री',
    'paper.mode': 'पेपर मोड',
    'live.mode': 'लाइव मोड',
    'virtual.balance': 'वर्चुअल बैलेंस',
    'simulate.trading': 'वास्तविक पैसे के बिना ट्रेडिंग का अनुकरण करें',
    'real.trading': 'वास्तविक फंड के साथ वास्तविक ट्रेडिंग',
    
    // Markets
    'scan.markets.opportunities': 'ट्रेडिंग अवसरों के लिए बाजारों को स्कैन करें',
    'scan.results': 'स्कैन परिणाम',
    'vol': 'वॉल्यूम',
    'top.gainers': 'टॉप गेनर्स',
    'top.losers': 'टॉप लूजर्स',
    'most.active': 'सबसे सक्रिय',
    'trending.coins': 'ट्रेंडिंग कॉइन्स',
    'market.cap': 'मार्केट कैप',
    'volume.24h': 'वॉल्यूम 24h',
    'change.24h': 'परिवर्तन 24h',
    
    // Exchange & API
    'connect.manage.exchanges': 'अपने एक्सचेंज खातों को कनेक्ट और प्रबंधित करें',
    'add.new.exchange': 'नया एक्सचेंज जोड़ें',
    'connected.exchanges': 'कनेक्टेड एक्सचेंजेस',
    'exchange.name': 'एक्सचेंज का नाम',
    'api.status': 'एपीआई स्थिति',
    'last.sync': 'अंतिम सिंक',
    'actions': 'क्रियाएं',
    'connected': 'कनेक्टेड',
    'disconnected': 'डिस्कनेक्टेड',
    'configure': 'कॉन्फ़िगर करें',
    'disconnect': 'डिस्कनेक्ट करें',
    'select.exchange': 'एक्सचेंज चुनें',
    'api.key': 'एपीआई की',
    'api.secret': 'एपीआई सीक्रेट',
    'passphrase': 'पासफ्रेज',
    'sandbox.mode': 'सैंडबॉक्स मोड',
    'test.connection': 'कनेक्शन टेस्ट करें',
    'save.configuration': 'कॉन्फ़िगरेशन सेव करें',
    
    // Alerts
    'create.new.alert': 'नया अलर्ट बनाएं',
    'manage.price.alerts': 'अपने मूल्य अलर्ट और नोटिफिकेशन प्रबंधित करें',
    'asset': 'एसेट',
    'condition': 'स्थिति',
    'target.price': 'लक्ष्य मूल्य',
    'notification.method': 'नोटिफिकेशन विधि',
    'alert.name': 'अलर्ट का नाम',
    'select.asset': 'एसेट चुनें',
    'select.condition': 'स्थिति चुनें',
    'above': 'से ऊपर',
    'below': 'से नीचे',
    'email': 'ईमेल',
    'push': 'पुश',
    'sms': 'एसएमएस',
    'create.alert': 'अलर्ट बनाएं',
    'active.alerts': 'सक्रिय अलर्ट्स',
    'triggered.alerts': 'ट्रिगर्ड अलर्ट्स',
    'current.price': 'वर्तमान मूल्य',
    'status': 'स्थिति',
    'triggered': 'ट्रिगर्ड',
    
    // Strategy Builder
    'create.custom.strategies': 'अपनी कस्टम ट्रेडिंग रणनीतियां बनाएं और अनुकूलित करें',
    'strategy.name': 'रणनीति का नाम',
    'enter.strategy.name': 'रणनीति का नाम दर्ज करें',
    'timeframe': 'समय सीमा',
    'select.timeframe': 'समय सीमा चुनें',
    'entry.conditions': 'प्रवेश की शर्तें',
    'exit.conditions': 'निकास की शर्तें',
    'risk.management': 'जोखिम प्रबंधन',
    'add.condition': 'शर्त जोड़ें',
    'stop.loss': 'स्टॉप लॉस (%)',
    'take.profit': 'टेक प्रॉफिट (%)',
    'save.strategy': 'रणनीति सेव करें',
    'test.strategy': 'रणनीति टेस्ट करें',
    'my.strategies': 'मेरी रणनीतियां',
    'public.strategies': 'सार्वजनिक रणनीतियां',
    'strategy.performance': 'रणनीति प्रदर्शन',
    'backtest.results': 'बैकटेस्ट परिणाम',
    
    // Settings
    'account.settings': 'खाता सेटिंग्स',
    'security.settings': 'सुरक्षा सेटिंग्स',
    'appearance': 'दिखावट',
    'language': 'भाषा',
    'select.language': 'भाषा चुनें',
    'dark.mode': 'डार्क मोड',
    'light.mode': 'लाइट मोड',
    'system': 'सिस्टम',
    'notifications': 'नोटिफिकेशन',
    'enable.notifications': 'नोटिफिकेशन सक्षम करें',
    'save.changes': 'बदलाव सेव करें',
    'change.password': 'पासवर्ड बदलें',
    'current.password': 'वर्तमान पासवर्ड',
    'new.password': 'नया पासवर्ड',
    'confirm.password': 'पासवर्ड की पुष्टि करें',
    'update.password': 'पासवर्ड अपडेट करें',
    
    // Help & Support
    'get.help.support': 'प्लेटफॉर्म का उपयोग करने के लिए सहायता और समर्थन प्राप्त करें',
    'frequently.asked.questions': 'अक्सर पूछे जाने वाले प्रश्न',
    'contact.support': 'सहायता से संपर्क करें',
    'user.guides': 'उपयोगकर्ता गाइड',
    'how.to.create.bot': 'मैं ट्रेडिंग बॉट कैसे बनाऊं?',
    'how.to.connect.exchange': 'मैं अपना एक्सचेंज कैसे कनेक्ट करूं?',
    'how.to.set.alerts': 'मैं मूल्य अलर्ट कैसे सेट करूं?',
    'getting.started.guide': 'शुरुआती गाइड',
    'advanced.trading.guide': 'एडवांस्ड ट्रेडिंग गाइड',
    'api.documentation': 'एपीआई दस्तावेज़ीकरण',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'सहायता समय: 24/7',
    'subject': 'विषय',
    'message': 'संदेश',
    'send.message': 'संदेश भेजें',
    'watch.tutorial': 'ट्यूटोरियल देखें',
    'view.guide': 'गाइड देखें',
  },
  de: {
    // Dashboard
    'dashboard': 'Dashboard',
    'welcome.back': 'Willkommen zurück! Hier ist was mit Ihrem Trading passiert.',
    
    // Navigation
    'my.bots': 'Meine Bots',
    'create.new.bot': 'Neuen Bot erstellen',
    'bot.templates': 'Bot-Vorlagen',
    'strategy.builder': 'Strategie-Builder',
    'saved.strategies': 'Gespeicherte Strategien',
    'strategy.marketplace': 'Strategie-Marktplatz',
    'build.strategy': 'Strategie erstellen',
    'market.overview': 'Marktübersicht',
    'market.scanner': 'Markt-Scanner',
    'live.charts': 'Live-Charts',
    'watchlist': 'Watchlist',
    'price.alerts': 'Preis-Alarme',
    'manual.trading': 'Manueller Handel',
    'signal.trading': 'Signal-Trading',
    'paper.trading': 'Paper Trading',
    'exchanges': 'Börsen',
    'exchanges.api': 'Börsen & API',
    'sync.balances': 'Guthaben synchronisieren',
    'alerts': 'Alarme',
    'alert.logs': 'Alarm-Protokolle',
    'create.alert': 'Alarm erstellen',
    'notification.settings': 'Benachrichtigungseinstellungen',
    'backtesting': 'Backtesting',
    'performance': 'Performance',
    'api.management': 'API-Verwaltung',
    'session.logs': 'Sitzungsprotokolle',
    'profile.settings': 'Profileinstellungen',
    'theme.settings': 'Theme-Einstellungen',
    'two.factor.auth': 'Zwei-Faktor-Authentifizierung',
    'help': 'Hilfe',
    'documentation': 'Dokumentation',
    'community': 'Community',
    'contact.support': 'Support kontaktieren',
    'bug.reports': 'Fehlerberichte',
    
    // Bot related
    'bot.name': 'Bot-Name',
    'trading.pair': 'Trading-Paar',
    'strategy.type': 'Strategie-Typ',
    'investment.amount': 'Investitionsbetrag',
    'enter.bot.name': 'Bot-Namen eingeben',
    'select.trading.pair': 'Trading-Paar auswählen',
    'select.strategy': 'Strategie auswählen',
    'enter.amount.usdt': 'Betrag in USDT eingeben',
    'create.bot': 'Bot erstellen',
    'manage.monitor.bots': 'Verwalten und überwachen Sie Ihre Trading-Bots',
    'active': 'Aktiv',
    'paused': 'Pausiert',
    'error': 'Fehler',
    'profit': 'Gewinn',
    'roi': 'ROI',
    'trades': 'Trades',
    'created': 'Erstellt',
    'pause': 'Pausieren',
    'start': 'Starten',
    'total.bots': 'Gesamt Bots',
    'bot.performance': 'Bot-Performance',
    'detailed.performance.metrics': 'Detaillierte Performance-Metriken für Ihre Bots',
    
    // Templates
    'strategy.templates': 'Strategie-Vorlagen',
    'preconfigured.bot.strategies': 'Vorkonfigurierte Bot-Strategien bereit zur Nutzung',
    'use.template': 'Vorlage verwenden',
    
    // Trading
    'buy': 'Kaufen',
    'sell': 'Verkaufen',
    'hold': 'Halten',
    'strong.buy': 'Starker Kauf',
    'amount': 'Betrag',
    'price': 'Preis',
    'total': 'Gesamt',
    'market': 'Markt',
    'limit': 'Limit',
    'order.type': 'Order-Typ',
    'place.order': 'Order platzieren',
    'order.book': 'Orderbuch',
    'recent.trades': 'Aktuelle Trades',
    'open.positions': 'Offene Positionen',
    'order.history': 'Order-Historie',
    'paper.mode': 'Paper-Modus',
    'live.mode': 'Live-Modus',
    'virtual.balance': 'Virtuelles Guthaben',
    'simulate.trading': 'Trading ohne echtes Geld simulieren',
    'real.trading': 'Echtes Trading mit echten Mitteln',
    
    // Markets
    'scan.markets.opportunities': 'Märkte nach Trading-Möglichkeiten scannen',
    'scan.results': 'Scan-Ergebnisse',
    'vol': 'Vol',
    'top.gainers': 'Top-Gewinner',
    'top.losers': 'Top-Verlierer',
    'most.active': 'Aktivste',
    'trending.coins': 'Trending Coins',
    'market.cap': 'Marktkapitalisierung',
    'volume.24h': 'Volumen 24h',
    'change.24h': 'Änderung 24h',
    
    // Exchange & API
    'connect.manage.exchanges': 'Verbinden und verwalten Sie Ihre Börsenkonten',
    'add.new.exchange': 'Neue Börse hinzufügen',
    'connected.exchanges': 'Verbundene Börsen',
    'exchange.name': 'Börsenname',
    'api.status': 'API-Status',
    'last.sync': 'Letzte Synchronisation',
    'actions': 'Aktionen',
    'connected': 'Verbunden',
    'disconnected': 'Getrennt',
    'configure': 'Konfigurieren',
    'disconnect': 'Trennen',
    'select.exchange': 'Börse auswählen',
    'api.key': 'API-Schlüssel',
    'api.secret': 'API-Geheimnis',
    'passphrase': 'Passphrase',
    'sandbox.mode': 'Sandbox-Modus',
    'test.connection': 'Verbindung testen',
    'save.configuration': 'Konfiguration speichern',
    
    // Alerts
    'create.new.alert': 'Neuen Alarm erstellen',
    'manage.price.alerts': 'Verwalten Sie Ihre Preis-Alarme und Benachrichtigungen',
    'asset': 'Asset',
    'condition': 'Bedingung',
    'target.price': 'Zielpreis',
    'notification.method': 'Benachrichtigungsmethode',
    'alert.name': 'Alarm-Name',
    'select.asset': 'Asset auswählen',
    'select.condition': 'Bedingung auswählen',
    'above': 'Über',
    'below': 'Unter',
    'email': 'E-Mail',
    'push': 'Push',
    'sms': 'SMS',
    'create.alert': 'Alarm erstellen',
    'active.alerts': 'Aktive Alarme',
    'triggered.alerts': 'Ausgelöste Alarme',
    'current.price': 'Aktueller Preis',
    'status': 'Status',
    'triggered': 'Ausgelöst',
    
    // Strategy Builder
    'create.custom.strategies': 'Erstellen und anpassen Sie Ihre Trading-Strategien',
    'strategy.name': 'Strategie-Name',
    'enter.strategy.name': 'Strategie-Namen eingeben',
    'timeframe': 'Zeitrahmen',
    'select.timeframe': 'Zeitrahmen auswählen',
    'entry.conditions': 'Einstiegsbedingungen',
    'exit.conditions': 'Ausstiegsbedingungen',
    'risk.management': 'Risikomanagement',
    'add.condition': 'Bedingung hinzufügen',
    'stop.loss': 'Stop Loss (%)',
    'take.profit': 'Take Profit (%)',
    'save.strategy': 'Strategie speichern',
    'test.strategy': 'Strategie testen',
    'my.strategies': 'Meine Strategien',
    'public.strategies': 'Öffentliche Strategien',
    'strategy.performance': 'Strategie-Performance',
    'backtest.results': 'Backtest-Ergebnisse',
    
    // Settings
    'account.settings': 'Kontoeinstellungen',
    'security.settings': 'Sicherheitseinstellungen',
    'appearance': 'Aussehen',
    'language': 'Sprache',
    'select.language': 'Sprache auswählen',
    'dark.mode': 'Dunkler Modus',
    'light.mode': 'Heller Modus',
    'system': 'System',
    'notifications': 'Benachrichtigungen',
    'enable.notifications': 'Benachrichtigungen aktivieren',
    'save.changes': 'Änderungen speichern',
    'change.password': 'Passwort ändern',
    'current.password': 'Aktuelles Passwort',
    'new.password': 'Neues Passwort',
    'confirm.password': 'Passwort bestätigen',
    'update.password': 'Passwort aktualisieren',
    
    // Help & Support
    'get.help.support': 'Erhalten Sie Hilfe und Support für die Nutzung der Plattform',
    'frequently.asked.questions': 'Häufig gestellte Fragen',
    'contact.support': 'Support kontaktieren',
    'user.guides': 'Benutzerhandbücher',
    'how.to.create.bot': 'Wie erstelle ich einen Trading-Bot?',
    'how.to.connect.exchange': 'Wie verbinde ich meine Börse?',
    'how.to.set.alerts': 'Wie richte ich Preis-Alarme ein?',
    'getting.started.guide': 'Erste Schritte',
    'advanced.trading.guide': 'Erweiterte Trading-Anleitung',
    'api.documentation': 'API-Dokumentation',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'Support-Zeiten: 24/7',
    'subject': 'Betreff',
    'message': 'Nachricht',
    'send.message': 'Nachricht senden',
    'watch.tutorial': 'Tutorial ansehen',
    'view.guide': 'Anleitung anzeigen',
  },
  pt: {
    // Dashboard
    'dashboard': 'Painel',
    'welcome.back': 'Bem-vindo de volta! Aqui está o que está acontecendo com seu trading.',
    
    // Navigation
    'my.bots': 'Meus Bots',
    'create.new.bot': 'Criar Novo Bot',
    'bot.templates': 'Modelos de Bot',
    'strategy.builder': 'Construtor de Estratégia',
    'saved.strategies': 'Estratégias Salvas',
    'strategy.marketplace': 'Mercado de Estratégias',
    'build.strategy': 'Construir Estratégia',
    'market.overview': 'Visão Geral do Mercado',
    'market.scanner': 'Scanner de Mercado',
    'live.charts': 'Gráficos ao Vivo',
    'watchlist': 'Lista de Observação',
    'price.alerts': 'Alertas de Preço',
    'manual.trading': 'Trading Manual',
    'signal.trading': 'Trading de Sinais',
    'paper.trading': 'Trading Virtual',
    'exchanges': 'Corretoras',
    'exchanges.api': 'Corretoras e API',
    'sync.balances': 'Sincronizar Saldos',
    'alerts': 'Alertas',
    'alert.logs': 'Logs de Alertas',
    'create.alert': 'Criar Alerta',
    'notification.settings': 'Configurações de Notificação',
    'backtesting': 'Backtesting',
    'performance': 'Performance',
    'api.management': 'Gerenciamento de API',
    'session.logs': 'Logs de Sessão',
    'profile.settings': 'Configurações de Perfil',
    'theme.settings': 'Configurações de Tema',
    'two.factor.auth': 'Autenticação de Dois Fatores',
    'help': 'Ajuda',
    'documentation': 'Documentação',
    'community': 'Comunidade',
    'contact.support': 'Contatar Suporte',
    'bug.reports': 'Relatórios de Bugs',
    
    // Bot related
    'bot.name': 'Nome do Bot',
    'trading.pair': 'Par de Trading',
    'strategy.type': 'Tipo de Estratégia',
    'investment.amount': 'Valor do Investimento',
    'enter.bot.name': 'Digite o nome do bot',
    'select.trading.pair': 'Selecione o par de trading',
    'select.strategy': 'Selecione a estratégia',
    'enter.amount.usdt': 'Digite o valor em USDT',
    'create.bot': 'Criar Bot',
    'manage.monitor.bots': 'Gerencie e monitore seus bots de trading',
    'active': 'Ativo',
    'paused': 'Pausado',
    'error': 'Erro',
    'profit': 'Lucro',
    'roi': 'ROI',
    'trades': 'Negociações',
    'created': 'Criado',
    'pause': 'Pausar',
    'start': 'Iniciar',
    'total.bots': 'Total de Bots',
    'bot.performance': 'Performance do Bot',
    'detailed.performance.metrics': 'Métricas detalhadas de performance para seus bots',
    
    // Templates
    'strategy.templates': 'Modelos de Estratégia',
    'preconfigured.bot.strategies': 'Estratégias de bot pré-configuradas prontas para uso',
    'use.template': 'Usar Modelo',
    
    // Trading
    'buy': 'Comprar',
    'sell': 'Vender',
    'hold': 'Manter',
    'strong.buy': 'Compra Forte',
    'amount': 'Quantidade',
    'price': 'Preço',
    'total': 'Total',
    'market': 'Mercado',
    'limit': 'Limite',
    'order.type': 'Tipo de Ordem',
    'place.order': 'Executar Ordem',
    'order.book': 'Livro de Ofertas',
    'recent.trades': 'Negociações Recentes',
    'open.positions': 'Posições Abertas',
    'order.history': 'Histórico de Ordens',
    'paper.mode': 'Modo Virtual',
    'live.mode': 'Modo Real',
    'virtual.balance': 'Saldo Virtual',
    'simulate.trading': 'Simular trading sem dinheiro real',
    'real.trading': 'Trading real com fundos reais',
    
    // Markets
    'scan.markets.opportunities': 'Escanear mercados em busca de oportunidades de trading',
    'scan.results': 'Resultados do Scan',
    'vol': 'Vol',
    'top.gainers': 'Maiores Altas',
    'top.losers': 'Maiores Baixas',
    'most.active': 'Mais Ativos',
    'trending.coins': 'Moedas em Tendência',
    'market.cap': 'Cap. de Mercado',
    'volume.24h': 'Volume 24h',
    'change.24h': 'Mudança 24h',
    
    // Exchange & API
    'connect.manage.exchanges': 'Conecte e gerencie suas contas de corretoras',
    'add.new.exchange': 'Adicionar Nova Corretora',
    'connected.exchanges': 'Corretoras Conectadas',
    'exchange.name': 'Nome da Corretora',
    'api.status': 'Status da API',
    'last.sync': 'Última Sincronização',
    'actions': 'Ações',
    'connected': 'Conectado',
    'disconnected': 'Desconectado',
    'configure': 'Configurar',
    'disconnect': 'Desconectar',
    'select.exchange': 'Selecionar Corretora',
    'api.key': 'Chave API',
    'api.secret': 'Segredo API',
    'passphrase': 'Frase de Acesso',
    'sandbox.mode': 'Modo Sandbox',
    'test.connection': 'Testar Conexão',
    'save.configuration': 'Salvar Configuração',
    
    // Alerts
    'create.new.alert': 'Criar Novo Alerta',
    'manage.price.alerts': 'Gerencie seus alertas de preço e notificações',
    'asset': 'Ativo',
    'condition': 'Condição',
    'target.price': 'Preço Alvo',
    'notification.method': 'Método de Notificação',
    'alert.name': 'Nome do Alerta',
    'select.asset': 'Selecionar Ativo',
    'select.condition': 'Selecionar Condição',
    'above': 'Acima',
    'below': 'Abaixo',
    'email': 'E-mail',
    'push': 'Push',
    'sms': 'SMS',
    'create.alert': 'Criar Alerta',
    'active.alerts': 'Alertas Ativos',
    'triggered.alerts': 'Alertas Disparados',
    'current.price': 'Preço Atual',
    'status': 'Status',
    'triggered': 'Disparado',
    
    // Strategy Builder
    'create.custom.strategies': 'Crie e personalize suas estratégias de trading',
    'strategy.name': 'Nome da Estratégia',
    'enter.strategy.name': 'Digite o nome da estratégia',
    'timeframe': 'Período',
    'select.timeframe': 'Selecionar período',
    'entry.conditions': 'Condições de Entrada',
    'exit.conditions': 'Condições de Saída',
    'risk.management': 'Gerenciamento de Risco',
    'add.condition': 'Adicionar Condição',
    'stop.loss': 'Stop Loss (%)',
    'take.profit': 'Take Profit (%)',
    'save.strategy': 'Salvar Estratégia',
    'test.strategy': 'Testar Estratégia',
    'my.strategies': 'Minhas Estratégias',
    'public.strategies': 'Estratégias Públicas',
    'strategy.performance': 'Performance da Estratégia',
    'backtest.results': 'Resultados do Backtest',
    
    // Settings
    'account.settings': 'Configurações da Conta',
    'security.settings': 'Configurações de Segurança',
    'appearance': 'Aparência',
    'language': 'Idioma',
    'select.language': 'Selecionar Idioma',
    'dark.mode': 'Modo Escuro',
    'light.mode': 'Modo Claro',
    'system': 'Sistema',
    'notifications': 'Notificações',
    'enable.notifications': 'Habilitar Notificações',
    'save.changes': 'Salvar Alterações',
    'change.password': 'Alterar Senha',
    'current.password': 'Senha Atual',
    'new.password': 'Nova Senha',
    'confirm.password': 'Confirmar Senha',
    'update.password': 'Atualizar Senha',
    
    // Help & Support
    'get.help.support': 'Obtenha ajuda e suporte para usar a plataforma',
    'frequently.asked.questions': 'Perguntas Frequentes',
    'contact.support': 'Contatar Suporte',
    'user.guides': 'Guias do Usuário',
    'how.to.create.bot': 'Como criar um bot de trading?',
    'how.to.connect.exchange': 'Como conectar minha corretora?',
    'how.to.set.alerts': 'Como configurar alertas de preço?',
    'getting.started.guide': 'Guia de Início',
    'advanced.trading.guide': 'Guia de Trading Avançado',
    'api.documentation': 'Documentação da API',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': 'Horário de Suporte: 24/7',
    'subject': 'Assunto',
    'message': 'Mensagem',
    'send.message': 'Enviar Mensagem',
    'watch.tutorial': 'Assistir Tutorial',
    'view.guide': 'Ver Guia',
  },
  zh: {
    // Dashboard
    'dashboard': '仪表板',
    'welcome.back': '欢迎回来！这是您的交易情况。',
    
    // Navigation
    'my.bots': '我的机器人',
    'create.new.bot': '创建新机器人',
    'bot.templates': '机器人模板',
    'strategy.builder': '策略构建器',
    'saved.strategies': '已保存策略',
    'strategy.marketplace': '策略市场',
    'build.strategy': '构建策略',
    'market.overview': '市场概览',
    'market.scanner': '市场扫描器',
    'live.charts': '实时图表',
    'watchlist': '关注列表',
    'price.alerts': '价格提醒',
    'manual.trading': '手动交易',
    'signal.trading': '信号交易',
    'paper.trading': '模拟交易',
    'exchanges': '交易所',
    'exchanges.api': '交易所与API',
    'sync.balances': '同步余额',
    'alerts': '提醒',
    'alert.logs': '提醒日志',
    'create.alert': '创建提醒',
    'notification.settings': '通知设置',
    'backtesting': '回测',
    'performance': '表现',
    'api.management': 'API管理',
    'session.logs': '会话日志',
    'profile.settings': '个人资料设置',
    'theme.settings': '主题设置',
    'two.factor.auth': '双因素认证',
    'help': '帮助',
    'documentation': '文档',
    'community': '社区',
    'contact.support': '联系支持',
    'bug.reports': '错误报告',
    
    // Bot related
    'bot.name': '机器人名称',
    'trading.pair': '交易对',
    'strategy.type': '策略类型',
    'investment.amount': '投资金额',
    'enter.bot.name': '输入机器人名称',
    'select.trading.pair': '选择交易对',
    'select.strategy': '选择策略',
    'enter.amount.usdt': '输入USDT金额',
    'create.bot': '创建机器人',
    'manage.monitor.bots': '管理和监控您的交易机器人',
    'active': '活跃',
    'paused': '暂停',
    'error': '错误',
    'profit': '利润',
    'roi': '投资回报率',
    'trades': '交易',
    'created': '创建时间',
    'pause': '暂停',
    'start': '开始',
    'total.bots': '总机器人数',
    'bot.performance': '机器人表现',
    'detailed.performance.metrics': '您的机器人的详细性能指标',
    
    // Templates
    'strategy.templates': '策略模板',
    'preconfigured.bot.strategies': '预配置的机器人策略，可直接使用',
    'use.template': '使用模板',
    
    // Trading
    'buy': '买入',
    'sell': '卖出',
    'hold': '持有',
    'strong.buy': '强力买入',
    'amount': '数量',
    'price': '价格',
    'total': '总计',
    'market': '市价',
    'limit': '限价',
    'order.type': '订单类型',
    'place.order': '下单',
    'order.book': '订单簿',
    'recent.trades': '最近交易',
    'open.positions': '持仓',
    'order.history': '订单历史',
    'paper.mode': '模拟模式',
    'live.mode': '实盘模式',
    'virtual.balance': '虚拟余额',
    'simulate.trading': '无真实资金的模拟交易',
    'real.trading': '使用真实资金的实盘交易',
    
    // Markets
    'scan.markets.opportunities': '扫描市场寻找交易机会',
    'scan.results': '扫描结果',
    'vol': '成交量',
    'top.gainers': '涨幅榜',
    'top.losers': '跌幅榜',
    'most.active': '最活跃',
    'trending.coins': '热门币种',
    'market.cap': '市值',
    'volume.24h': '24小时成交量',
    'change.24h': '24小时涨跌',
    
    // Exchange & API
    'connect.manage.exchanges': '连接和管理您的交易所账户',
    'add.new.exchange': '添加新交易所',
    'connected.exchanges': '已连接交易所',
    'exchange.name': '交易所名称',
    'api.status': 'API状态',
    'last.sync': '最后同步',
    'actions': '操作',
    'connected': '已连接',
    'disconnected': '已断开',
    'configure': '配置',
    'disconnect': '断开连接',
    'select.exchange': '选择交易所',
    'api.key': 'API密钥',
    'api.secret': 'API密码',
    'passphrase': '密码短语',
    'sandbox.mode': '沙盒模式',
    'test.connection': '测试连接',
    'save.configuration': '保存配置',
    
    // Alerts
    'create.new.alert': '创建新提醒',
    'manage.price.alerts': '管理您的价格提醒和通知',
    'asset': '资产',
    'condition': '条件',
    'target.price': '目标价格',
    'notification.method': '通知方式',
    'alert.name': '提醒名称',
    'select.asset': '选择资产',
    'select.condition': '选择条件',
    'above': '高于',
    'below': '低于',
    'email': '邮件',
    'push': '推送',
    'sms': '短信',
    'create.alert': '创建提醒',
    'active.alerts': '活跃提醒',
    'triggered.alerts': '已触发提醒',
    'current.price': '当前价格',
    'status': '状态',
    'triggered': '已触发',
    
    // Strategy Builder
    'create.custom.strategies': '创建和自定义您的交易策略',
    'strategy.name': '策略名称',
    'enter.strategy.name': '输入策略名称',
    'timeframe': '时间框架',
    'select.timeframe': '选择时间框架',
    'entry.conditions': '入场条件',
    'exit.conditions': '出场条件',
    'risk.management': '风险管理',
    'add.condition': '添加条件',
    'stop.loss': '止损(%)',
    'take.profit': '止盈(%)',
    'save.strategy': '保存策略',
    'test.strategy': '测试策略',
    'my.strategies': '我的策略',
    'public.strategies': '公共策略',
    'strategy.performance': '策略表现',
    'backtest.results': '回测结果',
    
    // Settings
    'account.settings': '账户设置',
    'security.settings': '安全设置',
    'appearance': '外观',
    'language': '语言',
    'select.language': '选择语言',
    'dark.mode': '深色模式',
    'light.mode': '浅色模式',
    'system': '系统',
    'notifications': '通知',
    'enable.notifications': '启用通知',
    'save.changes': '保存更改',
    'change.password': '更改密码',
    'current.password': '当前密码',
    'new.password': '新密码',
    'confirm.password': '确认密码',
    'update.password': '更新密码',
    
    // Help & Support
    'get.help.support': '获取使用平台的帮助和支持',
    'frequently.asked.questions': '常见问题',
    'contact.support': '联系支持',
    'user.guides': '用户指南',
    'how.to.create.bot': '如何创建交易机器人？',
    'how.to.connect.exchange': '如何连接我的交易所？',
    'how.to.set.alerts': '如何设置价格提醒？',
    'getting.started.guide': '入门指南',
    'advanced.trading.guide': '高级交易指南',
    'api.documentation': 'API文档',
    'support.email': 'support@cryptobotpro.com',
    'support.hours': '支持时间：24/7',
    'subject': '主题',
    'message': '消息',
    'send.message': '发送消息',
    'watch.tutorial': '观看教程',
    'view.guide': '查看指南',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'en';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
    document.documentElement.lang = language;
    document.documentElement.dir = language === 'ar' ? 'rtl' : 'ltr';
  }, [language]);

  const t = (key: string): string => {
    return translations[language][key] || translations.en[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
